const ACCESSORIES = [
  {
    id: 4101,
    productCode: "GG-LB-MID-01",
    title: "MIDNIGHT",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Experience elegance and durability with this AAA premium leather belt. Sleek black finish with refined stitching makes it perfect for formal and casual wear.",
    longDescription:
      "Midnight Leather Belt is crafted from premium leather, combining elegance, durability, and comfort. Ideal for both formal and casual attire.",
    feature: [
      "100% Premium Leather: Luxurious texture and finish",
      "Durable & Comfortable: Soft yet long-lasting leather",
      "Adjustable Fit: Multiple holes for customized sizing",
      "Elegant Stitching: Adds style and strength",
      "Moisture-Resistant Lining: Comfortable in any condition",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/1Midnight-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4102,
    productCode: "GG-LB-CBL-02",
    title: "CLASSIC BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Timeless style meets premium craftsmanship. Perfect for office wear or special events.",
    longDescription:
      "Classic Black Leather Belt is the epitome of sophistication, made from 100% premium leather. Elegant stitching ensures durability and style for any formal outfit.",
    feature: [
      "100% Premium Leather: Smooth, high-quality material",
      "Comfort & Longevity: Soft yet resilient leather",
      "Custom Fit: Adjustable with precision-cut holes",
      "Elegant Stitching: Reinforces durability and style",
      "Moisture-Resistant Lining: All-day comfort",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/2ClassiceBlack-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4103,
    productCode: "GG-LB-C06-03",
    title: "CLASSIC 0601",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Perfect blend of traditional design and modern craftsmanship. Designed for men who value elegance and versatility.",
    longDescription:
      "Classic 0601 Leather Belt combines traditional design with modern craftsmanship for a versatile, stylish, and durable accessory.",
    feature: [
      "Premium Leather: Rich, long-lasting texture",
      "Soft & Durable: Comfort without compromising strength",
      "Adjustable Fit: Customizable sizing options",
      "Precision Stitching: Stylish and strong",
      "Moisture-Resistant Lining: Keeps you dry and comfortable",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/3Classic0601-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4104,
    productCode: "GG-LB-CBR-04",
    title: "CLASSIC BROWN",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "A versatile brown belt that pairs with casual and semi-formal outfits. Premium leather ensures elegance with every wear.",
    longDescription:
      "Classic Brown Leather Belt offers premium quality leather, elegant stitching, and adjustable fit for style and comfort.",
    feature: [
      "100% Premium Leather: Smooth and durable",
      "Comfort & Longevity: Soft feel for everyday wear",
      "Adjustable Fit: Multiple holes for perfect sizing",
      "Elegant Stitching: Strength and style combined",
      "Moisture-Resistant Lining: Reliable in any condition",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Brown",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/5ClassicBrown-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4105,
    productCode: "GG-LB-SCC-05",
    title: "STITCH CRAFT CLASSIC",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Designed with meticulous stitching, this belt delivers a sophisticated look while maintaining durability for long-term wear.",
    longDescription:
      "Stitch Craft Classic Leather Belt combines elegant decorative stitching with premium leather to create a stylish and durable accessory.",
    feature: [
      "Premium Leather: Soft and high-quality",
      "Durable & Comfortable: Perfect balance of comfort and strength",
      "Customizable Fit: Easily adjustable",
      "Decorative Stitching: Adds elegance",
      "Moisture-Resistant Lining: Keeps the belt in pristine condition",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Brown",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/6StitchCraftClassic-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4106,
    productCode: "GG-LB-ES-06",
    title: "ESSENTIAL STRAP",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "A minimalistic belt designed for daily wear. Premium leather and sleek buckle make it perfect for casual and business casual outfits.",
    longDescription:
      "Essential Strap Leather Belt offers a clean, minimalist design crafted from premium leather for comfort and durability in daily use.",
    feature: [
      "100% Premium Leather: Smooth, high-quality finish",
      "Durable & Comfortable: Ideal for regular use",
      "Adjustable Fit: Multiple holes for a perfect fit",
      "Minimalist Stitching: Subtle yet stylish",
      "Moisture-Resistant Lining: Keeps belt fresh and dry",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/7EssentialStrap-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4107,
    productCode: "GG-LB-EBR-07",
    title: "ELEGANT BROWN",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Classic brown belt with a refined buckle, perfect for complementing business or formal attire with premium leather quality.",
    longDescription:
      "Elegant Brown Leather Belt features smooth premium leather, adjustable fit, and refined stitching for business or formal wear.",
    feature: [
      "Premium Leather: Smooth and luxurious",
      "Comfort & Longevity: Designed for all-day wear",
      "Customizable Fit: Adjustable for any waist size",
      "Refined Stitching: Elegant and durable",
      "Moisture-Resistant Lining: Reliable comfort",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Brown",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/8ElegantBrown-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4108,
    productCode: "GG-LB-UBL-08",
    title: "U BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern urban design meets premium leather craftsmanship. Sleek black belt ideal for casual and formal ensembles.",
    longDescription:
      "U Black Leather Belt is designed for modern urban fashion with smooth leather, subtle stitching, and adjustable sizing for comfort and style.",
    feature: [
      "Premium Leather: Smooth, long-lasting quality",
      "Comfortable Fit: Soft yet durable",
      "Adjustable Sizing: Multiple precision holes",
      "Stylish Stitching: Subtle elegance",
      "Moisture-Resistant Lining: Perfect for daily wear",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/9UBlack-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4109,
    productCode: "GG-LB-EE-09",
    title: "EVERYDAY ESSENTIAL",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Classic belt for everyday wear. Comfortable premium leather with a simple, versatile design.",
    longDescription:
      "Everyday Essential Leather Belt combines classic styling and premium leather for comfort, durability, and versatility.",
    feature: [
      "100% Premium Leather: Smooth and long-lasting",
      "Durable & Comfortable: Soft feel for daily use",
      "Adjustable Fit: Precision-cut holes for perfect sizing",
      "Minimal Stitching: Clean, modern look",
      "Moisture-Resistant Lining: Keeps belt fresh and dry",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/10EverydayEssential-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4110,
    productCode: "GG-LB-CL-10",
    title: "CLASSIC LATCH",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Timeless belt with a modern latch buckle. Premium leather ensures durability and style for business and casual outfits.",
    longDescription:
      "Classic Latch Leather Belt combines timeless design with a modern buckle, premium leather, and elegant stitching for business or casual wear.",
    feature: [
      "Premium Leather: Smooth and high-quality",
      "Comfortable & Durable: Ideal for long-term wear",
      "Adjustable Fit: Multiple holes for precision sizing",
      "Elegant Stitching: Adds style and strength",
      "Moisture-Resistant Lining: Keeps belt pristine",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Latch Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/11ClassicLatch-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4111,
    productCode: "GG-LB-US-11",
    title: "URBAN SLEEK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern belt designed for urban fashion. Premium leather combined with a sleek buckle creates a polished, contemporary look.",
    longDescription:
      "Urban Sleek Leather Belt features modern styling, soft premium leather, adjustable sizing, and elegant stitching for urban wear.",
    feature: [
      "Premium Leather: Smooth and luxurious",
      "Comfortable Fit: Soft and flexible",
      "Adjustable Sizing: Multiple holes for perfect fit",
      "Modern Stitching: Sleek and stylish",
      "Moisture-Resistant Lining: Perfect for urban lifestyle",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/12UrbanSleek-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4112,
    productCode: "GG-LB-CM-12",
    title: "CNICH MARK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Stylish belt with distinctive marking details. Premium leather ensures durability while offering a unique, contemporary design.",
    longDescription:
      "Cinch Mark Leather Belt features high-quality leather, distinctive markings, adjustable sizing, and decorative stitching for style and durability.",
    feature: [
      "Premium Leather: High-quality finish",
      "Comfort & Strength: Durable yet soft",
      "Adjustable Fit: Multiple holes for precise sizing",
      "Decorative Stitching: Adds elegance and style",
      "Moisture-Resistant Lining: Comfortable all day",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Brown",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/13CinchMark-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4113,
    productCode: "GG-LB-CS-13",
    title: "CINNAMON STITCHED",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Elegant brown belt with decorative cinnamon stitching. Perfect for casual and semi-formal attire.",
    longDescription:
      "Cinnamon Stitched Leather Belt combines premium leather with elegant stitching for a stylish and durable everyday belt.",
    feature: [
      "Premium Leather: Smooth and luxurious",
      "Comfortable & Durable: Soft, long-lasting leather",
      "Adjustable Fit: Custom sizing options",
      "Decorative Stitching: Stylish and elegant",
      "Moisture-Resistant Lining: Keeps belt fresh",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Brown",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/14CinnamonStitched-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4114,
    productCode: "GG-LB-EC-14",
    title: "ETERNAL CRAFT",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Premium leather belt crafted for style and longevity. Elegant design perfect for both formal and casual outfits.",
    longDescription:
      "Eternal Craft Leather Belt is designed for long-lasting style, featuring premium leather, elegant stitching, and adjustable fit.",
    feature: [
      "100% Premium Leather: Soft and durable",
      "Comfort & Longevity: Ideal for long-term wear",
      "Adjustable Fit: Custom sizing options",
      "Elegant Stitching: Adds sophistication",
      "Moisture-Resistant Lining: Keeps belt comfortable",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/15Eternal Craft-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4115,
    productCode: "GG-LB-SB-15",
    title: "SLEEK BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern black belt with a sleek buckle design. Premium leather ensures durability and elegance for any outfit.",
    longDescription:
      "Sleek Black Leather Belt is crafted for modern style and comfort, made from premium leather with adjustable sizing and elegant stitching.",
    feature: [
      "Premium Leather: Smooth, long-lasting texture",
      "Comfortable & Durable: Soft and reliable",
      "Adjustable Fit: Multiple holes for custom sizing",
      "Elegant Stitching: Adds sophistication",
      "Moisture-Resistant Lining: Comfortable all day",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/16SleekBlack-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4116,
    productCode: "GG-LB-SL-16",
    title: "SLEEK LOCK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Premium belt with a modern locking buckle. Designed for style, comfort, and long-lasting performance.",
    longDescription:
      "Sleek Lock Leather Belt features a modern locking buckle, premium leather, and elegant stitching for a durable, stylish belt.",
    feature: [
      "100% Premium Leather: Smooth and luxurious finish",
      "Comfort & Durability: Soft yet strong leather",
      "Adjustable Fit: Multiple holes for precision sizing",
      "Modern Stitching: Adds elegance and strength",
      "Moisture-Resistant Lining: Keeps you comfortable all day",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Black",
      width: "3.5 cm",
      buckle: "Lock Metal",
      length: "Multiple sizes available",
    },
    imageUrl: ["/Leather-Belts/17SleekLock-Leather-Belt.jpg"],
    moq: 10,
  },

  // HERITAGE LONG WALLET BROWN GG-LW-HRT-BRN-22
  {
    id: 3101,
    productCode: "GG-LW-BIF-COG-01",
    title: "BIFOLD COGNAC",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A rich, warm cognac bifold featuring a distinct marbled grain and rugged character.",
    longDescription:
      "The Bifold Cognac Leather Wallet is crafted from pull-up leather that develops a beautiful patina over time. Its warm reddish-brown hues and visible natural textures make it a standout accessory for those who appreciate heritage styling.",
    feature: [
      "100% Full-Grain Cognac Leather",
      "Hand-Burnished Edges",
      "6 Precision-Cut Card Slots",
      "Reinforced Contrast Stitching",
    ],
    specifications: {
      material: "Full-Grain Leather",
      color: "Cognac",
      type: "Classic Bifold",
      dimensions: "11 x 9 cm",
      compartments: "2 Cash slots, 6 card pockets, 2 hidden receipts slots",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Cognac-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3102,
    productCode: "GG-LW-BIF-TAN-02",
    title: "BIFOLD TAN VINTAGE",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Lightweight and classic tan leather with a soft matte finish for a modern look.",
    longDescription:
      "This Bifold Tan Leather Wallet features a uniform, honey-colored finish. The interior showcases a traditional layout with symmetrical card slots, offering a balance between slim profile and high storage capacity.",
    feature: [
      "Premium Calfskin Leather",
      "Slim-Profile Design",
      "Tonal Heavy-Duty Stitching",
      "Dual Bill Compartments",
    ],
    specifications: {
      material: "Genuine Tan Leather",
      color: "Tan",
      type: "Bifold",
      dimensions: "11 x 9 cm",
      compartments: "6 Card slots, split currency section",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Tan-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3103,
    productCode: "GG-LW-BIF-BLU-03",
    title: "BIFOLD MIDNIGHT BLUE",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Sophisticated deep blue leather with a smooth, semi-gloss finish.",
    longDescription:
      "A modern alternative to black, the Midnight Blue Bifold offers a sleek, professional aesthetic.",
    feature: [
      "High-Grade Semi-Aniline Leather",
      "Moisture-Resistant Finish",
      "Edge-Painted for Durability",
      "Compact Fold Technology",
    ],
    specifications: {
      material: "Premium Leather",
      color: "Midnight Blue",
      type: "Slim Bifold",
      dimensions: "11 x 9 cm",
      compartments: "Multiple card slots, central cash sleeve",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Blue-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3104,
    productCode: "GG-LW-BIF-OXB-04",
    title: "BIFOLD OXBLOOD",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Bold burgundy tones in a premium smooth-finish leather for a touch of luxury.",
    longDescription:
      "The Oxblood Bifold is the epitome of elegance with a deep wine-red hue.",
    feature: [
      "Luxury Grade Oxblood Leather",
      "Scratch-Resistant Surface",
      "Symmetrical Interior Layout",
      "Feathered Edge Construction",
    ],
    specifications: {
      material: "Top-Grain Leather",
      color: "Oxblood",
      type: "Bifold",
      dimensions: "11 x 9 cm",
      compartments: "6 Card slots, 1 cash pocket",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Oxblood-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3105,
    productCode: "GG-LW-BIF-BRN-05",
    title: "BIFOLD BROWN WITH ID WINDOW",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Classic chocolate brown leather featuring a convenient transparent ID window.",
    longDescription:
      "Designed for maximum utility with quick-access ID window.",
    feature: [
      "Transparent ID/Photo Window",
      "Thumb-Slide Slot for Easy Card Removal",
      "Supple Textured Leather",
      "Extra Wide Cash Compartment",
    ],
    specifications: {
      material: "Premium Cowhide",
      color: "Chocolate Brown",
      type: "Bifold with ID Window",
      dimensions: "11.5 x 9.5 cm",
      compartments:
        "ID Window, 3 card slots, 2 hidden slots, large cash section",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Brown-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  // ---- Journeyman / TravelMan / Heritage ----
  {
    id: 3201,
    productCode: "GG-LW-JRN-BLK-17",
    title: "JOURNEYMAN BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A minimalist, ultra-slim card holder crafted from sleek black premium leather.",
    specifications: {
      material: "Premium Leather",
      color: "Black",
      type: "Slim Card Holder",
      dimensions: "10 x 7 cm",
      compartments: "2 External card slots, 1 central pocket",
    },
    imageUrl: ["/Leather-Wallets/Journeyman-Black-Leather-Wallet.jpg"],
    moq: 10,
  },
  {
    id: 3202,
    productCode: "GG-LW-JRN-BRN-18",
    title: "JOURNEYMAN BROWN",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Classic tan-brown card holder featuring an elegant, slim-line silhouette.",
    specifications: {
      material: "Genuine Leather",
      color: "Brown / Tan",
      type: "Slim Card Holder",
      dimensions: "10 x 7 cm",
      compartments: "2 External card slots, 1 central pocket",
    },
    imageUrl: ["/Leather-Wallets/Journeyman-Brown-Leather-Wallet.jpg"],
    moq: 10,
  },
  {
    id: 3203,
    productCode: "GG-LW-TRV-COG-19",
    title: "TRAVELMAN COGNAC",
    category: "accessories",
    subCat: "leather-wallets",
    description: "A sophisticated vertical bifold in rich cognac leather.",
    specifications: {
      material: "Premium Cognac Leather",
      color: "Cognac",
      type: "Vertical Bifold",
      dimensions: "11 x 8 cm",
      compartments: "3 Card slots, 1 vertical pocket, 1 large stash pocket",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Cognac-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3204,
    productCode: "GG-LW-TRV-BLK-20",
    title: "TRAVELMAN BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    description: "Professional vertical bifold wallet in sleek black leather.",
    specifications: {
      material: "Premium Black Leather",
      color: "Black",
      type: "Vertical Bifold",
      dimensions: "11 x 8 cm",
      compartments: "3 Card slots, 1 vertical pocket, 1 large stash pocket",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Black-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  {
    id: 3205,
    productCode: "GG-LW-HRT-BRN-21",
    title: "HERITAGE LONG WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    description: "A rugged, vintage-inspired long wallet with security chain.",
    specifications: {
      material: "Heavy-Duty Pull-Up Leather",
      color: "Vintage Brown",
      type: "Long Bifold with Chain",
      dimensions: "19 x 9 cm",
      compartments: "6 Card slots, 2 full-length bill sections",
    },
    imageUrl: ["/Leather-Wallets/Heritage-Long-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  {
    id: 3206,
    productCode: "GG-LW-HRT-BRN-22",
    title: "HERITAGE LONG WALLET BROWN",
    category: "accessories",
    subCat: "leather-wallets",
    description: "A rugged, vintage-inspired long wallet with security chain.",
    specifications: {
      material: "Heavy-Duty Pull-Up Leather",
      color: "Brown",
      type: "Long Bifold with Chain",
      dimensions: "19 x 9 cm",
      compartments: "6 Card slots, 2 full-length bill sections",
    },
    imageUrl: ["/Leather-Wallets/Heritage-Long-Brown-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  {
    id: 3208,
    productCode: "GG-SW-TRI-BLK-26",
    title: "CLASSIC LEATHER TRIFOLD WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A compact, traditional trifold design with a smooth finish and contrast stitching for a refined everyday carry.",
    specifications: {
      material: "Genuine Smooth Leather",
      color: "Black",
      type: "Trifold",
      dimensions: "11 x 8.5 cm",
      compartments: "1 ID window, 6 card slots, 1 large bill compartment",
    },
    imageUrl: ["/Leather-Wallets/Trifold-Black-Leather-Wallet-2.jpg"],
    moq: 20,
  },

  {
    id: 3209,
    productCode: "GG-TW-TRV-TAN-26",
    title: "TRAVELMAN PASSPORT WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Slim, vertical travel wallet designed to hold a passport and essential cards without the bulk of a traditional long wallet.",
    specifications: {
      material: "Premium Tan Leather",
      color: "Tan",
      type: "Vertical Passport/Travel Bifold",
      dimensions: "14 x 10 cm",
      compartments: "2 vertical passport/document pockets, 3 curved card slots",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Tan-Leather-Wallet-2.jpg"],
    moq: 15,
  },

  {
    id: 3210,
    productCode: "GG-LW-WRK-MB-26",
    title: "WORKMAN LONG WALLET BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A robust, high-capacity long wallet featuring a distinctive angular flap, dual snap closures, and a reinforced lanyard grommet for security chains.",
    specifications: {
      material: "Full-Grain Vegetable Tanned Leather",
      colors: ["Black", "Cognac", "Tan"],
      type: "Long Bifold / Biker Wallet",
      dimensions: "19.5 x 9.5 cm",
      compartments:
        "4 vertical card slots, 1 zippered coin pocket, 2 full-length bill compartments",
    },
    imageUrl: ["/Leather-Wallets/Workman-Black-Leather-Wallet-1.jpg"],
    moq: 10,
  },

  {
    id: 3211,
    productCode: "GG-LW-WRK-MC-26",
    title: "WORKMAN LONG WALLET Cognac",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A robust, high-capacity long wallet featuring a distinctive angular flap, dual snap closures, and a reinforced lanyard grommet for security chains.",
    specifications: {
      material: "Full-Grain Vegetable Tanned Leather",
      colors: ["Black", "Cognac", "Tan"],
      type: "Long Bifold / Biker Wallet",
      dimensions: "19.5 x 9.5 cm",
      compartments:
        "4 vertical card slots, 1 zippered coin pocket, 2 full-length bill compartments",
    },
    imageUrl: ["/Leather-Wallets/Workman-Cognac-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  {
    id: 3212,
    productCode: "GG-LW-WRK-MT-26",
    title: "WORKMAN LONG WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A robust, high-capacity long wallet featuring a distinctive angular flap, dual snap closures, and a reinforced lanyard grommet for security chains.",
    specifications: {
      material: "Full-Grain Vegetable Tanned Leather",
      colors: ["Black", "Cognac", "Tan"],
      type: "Long Bifold / Biker Wallet",
      dimensions: "19.5 x 9.5 cm",
      compartments:
        "4 vertical card slots, 1 zippered coin pocket, 2 full-length bill compartments",
    },
    imageUrl: ["/Leather-Wallets/Workman-Tan-Leather-Wallet-2.jpg"],
    moq: 10,
  },
];

export default ACCESSORIES;
