let ACCESSORIES = [
  // ------------------- Leather Belts -------------------

  {
    id: 4101,
    sku: "GG-LB-MID-01",
    leatherFinish: "Matte Finish",
    metaTitle: "Midnight Premium Leather Belt | Elegant Black Belt",
    metaDescription:
      "Shop the Midnight premium leather belt crafted with full-grain leather, durable metal buckle, and elegant stitching for formal and casual wear.",
    slug: "midnight-premium-leather-belt",
    relatedProducts: ["GG-LB-CBL-02", "GG-LB-EE-09", "GG-LB-SB-15"],
    productCode: "GG-LB-MID-01",
    title: "MIDNIGHT",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Experience elegance and durability with this AAA premium leather belt. Sleek black finish with refined stitching makes it perfect for formal and casual wear.",
    longDescription:
      "Midnight Leather Belt is crafted from premium leather, combining elegance, durability, and comfort. Ideal for both formal and casual attire.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/1Midnight-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4102,
    sku: "GG-LB-CBL-02",
    leatherFinish: "Smooth Finish",
    metaTitle: "Classic Black Leather Belt | Premium Formal Belt",
    metaDescription:
      "Classic Black premium leather belt with elegant stitching, adjustable sizing, and durable metal buckle for business and formal wear.",
    slug: "classic-black-leather-belt",
    relatedProducts: ["GG-LB-MID-01", "GG-LB-SB-15", "GG-LB-CL-10"],
    productCode: "GG-LB-CBL-02",
    title: "CLASSIC BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Timeless style meets premium craftsmanship. Perfect for office wear or special events.",
    longDescription:
      "Classic Black Leather Belt is the epitome of sophistication, made from 100% premium leather. Elegant stitching ensures durability and style for any formal outfit.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/2ClassicBlack-Leather-Belt.jpg"], // Removed spelling mistake 'Classice' if applicable
    moq: 10,
  },
  {
    id: 4103,
    sku: "GG-LB-C06-03",
    leatherFinish: "Classic Matte Finish",
    metaTitle: "Classic 0601 Leather Belt | Traditional Premium Belt",
    metaDescription:
      "Classic 0601 leather belt combines timeless design with premium craftsmanship for formal and casual styling.",
    slug: "classic-0601-leather-belt",
    relatedProducts: ["GG-LB-CBL-02", "GG-LB-EC-14", "GG-LB-US-11"],
    productCode: "GG-LB-C06-03",
    title: "CLASSIC 0601",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Perfect blend of traditional design and modern craftsmanship. Designed for men who value elegance and versatility.",
    longDescription:
      "Classic 0601 Leather Belt combines traditional design with modern craftsmanship for a versatile, stylish, and durable accessory.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/3Classic0601-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4104,
    sku: "GG-LB-CBR-04",
    leatherFinish: "Smooth Finish",
    metaTitle: "Classic Brown Leather Belt | Premium Brown Belt",
    metaDescription:
      "Elegant Classic Brown leather belt with durable premium leather and refined stitching for versatile everyday wear.",
    slug: "classic-brown-leather-belt",
    relatedProducts: ["GG-LB-EBR-07", "GG-LB-CS-13", "GG-LB-SCC-05"],
    productCode: "GG-LB-CBR-04",
    title: "CLASSIC BROWN",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "A versatile brown belt that pairs with casual and semi-formal outfits. Premium leather ensures elegance with every wear.",
    longDescription:
      "Classic Brown Leather Belt offers premium quality leather, elegant stitching, and adjustable fit for style and comfort.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/5ClassicBrown-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4105,
    sku: "GG-LB-SCC-05",
    leatherFinish: "Textured Finish",
    metaTitle: "Stitch Craft Classic Leather Belt | Decorative Stitch Belt",
    metaDescription:
      "Premium Stitch Craft Classic leather belt featuring decorative stitching, durable leather, and timeless elegance.",
    slug: "stitch-craft-classic-leather-belt",
    relatedProducts: ["GG-LB-CBR-04", "GG-LB-CS-13", "GG-LB-EC-14"],
    productCode: "GG-LB-SCC-05",
    title: "STITCH CRAFT CLASSIC",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Designed with meticulous stitching, this belt delivers a sophisticated look while maintaining durability for long-term wear.",
    longDescription:
      "Stitch Craft Classic Leather Belt combines elegant decorative stitching with premium leather to create a stylish and durable accessory.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/6StitchCraftClassic-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4106,
    sku: "GG-LB-ES-06",
    leatherFinish: "Minimal Matte Finish",
    metaTitle: "Essential Strap Leather Belt | Minimalist Leather Belt",
    metaDescription:
      "Essential Strap leather belt crafted with premium leather and minimalist styling for daily wear comfort.",
    slug: "essential-strap-leather-belt",
    relatedProducts: ["GG-LB-EE-09", "GG-LB-US-11", "GG-LB-MID-01"],
    productCode: "GG-LB-ES-06",
    title: "ESSENTIAL STRAP",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "A minimalistic belt designed for daily wear. Premium leather and sleek buckle make it perfect for casual and business casual outfits.",
    longDescription:
      "Essential Strap Leather Belt offers a clean, minimalist design crafted from premium leather for comfort and durability in daily use.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/7EssentialStrap-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4107,
    sku: "GG-LB-EBR-07",
    leatherFinish: "Semi-Gloss Finish",
    metaTitle: "Elegant Brown Leather Belt | Business Casual Belt",
    metaDescription:
      "Elegant Brown leather belt made with premium leather and refined stitching for formal and business outfits.",
    slug: "elegant-brown-leather-belt",
    relatedProducts: ["GG-LB-CBR-04", "GG-LB-CS-13", "GG-LB-SCC-05"],
    productCode: "GG-LB-EBR-07",
    title: "ELEGANT BROWN",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Classic brown belt with a refined buckle, perfect for complementing business or formal attire with premium leather quality.",
    longDescription:
      "Elegant Brown Leather Belt features smooth premium leather, adjustable fit, and refined stitching for business or formal wear.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/8ElegantBrown-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4108,
    sku: "GG-LB-UBL-08",
    leatherFinish: "Smooth Urban Finish",
    metaTitle: "U Black Leather Belt | Urban Style Leather Belt",
    metaDescription:
      "Modern U Black leather belt featuring sleek urban styling, premium leather, and comfortable adjustable sizing.",
    slug: "u-black-leather-belt",
    relatedProducts: ["GG-LB-US-11", "GG-LB-SB-15", "GG-LB-MID-01"],
    productCode: "GG-LB-UBL-08",
    title: "U BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern urban design meets premium leather craftsmanship. Sleek black belt ideal for casual and formal ensembles.",
    longDescription:
      "U Black Leather Belt is designed for modern urban fashion with smooth leather, subtle stitching, and adjustable sizing for comfort and style.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "40 mm", // Moved inside specifications to remain consistent
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/9UBlack-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4109,
    sku: "GG-LB-EE-09",
    leatherFinish: "Clean Matte Finish",
    metaTitle: "Everyday Essential Leather Belt | Daily Wear Belt",
    metaDescription:
      "Everyday Essential leather belt with premium leather construction and minimalist styling for regular use.",
    slug: "everyday-essential-leather-belt",
    relatedProducts: ["GG-LB-ES-06", "GG-LB-CBL-02", "GG-LB-SB-15"],
    productCode: "GG-LB-EE-09",
    title: "EVERYDAY ESSENTIAL",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Classic belt for everyday wear. Comfortable premium leather with a simple, versatile design.",
    longDescription:
      "Everyday Essential Leather Belt combines classic styling and premium leather for comfort, durability, and versatility.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/10EverydayEssential-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4110,
    sku: "GG-LB-CL-10",
    leatherFinish: "Polished Finish",
    metaTitle: "Classic Latch Leather Belt | Modern Latch Belt",
    metaDescription:
      "Classic Latch leather belt with modern latch buckle, premium leather, and elegant formal styling.",
    slug: "classic-latch-leather-belt",
    relatedProducts: ["GG-LB-CBL-02", "GG-LB-SL-16", "GG-LB-MID-01"],
    productCode: "GG-LB-CL-10",
    title: "CLASSIC LATCH",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Timeless belt with a modern latch buckle. Premium leather ensures durability and style for business and casual outfits.",
    longDescription:
      "Classic Latch Leather Belt combines timeless design with a modern buckle, premium leather, and elegant stitching for business or casual wear.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Latch Buckle", // Synced with the property outside previously
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/11ClassicLatch-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4111,
    sku: "GG-LB-US-11",
    leatherFinish: "Smooth Urban Finish",
    metaTitle: "Urban Sleek Leather Belt | Contemporary Urban Belt",
    metaDescription:
      "Urban Sleek leather belt designed with premium leather, sleek styling, and comfort for modern fashion.",
    slug: "urban-sleek-leather-belt",
    relatedProducts: ["GG-LB-UBL-08", "GG-LB-ES-06", "GG-LB-SB-15"],
    productCode: "GG-LB-US-11",
    title: "URBAN SLEEK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern belt designed for urban fashion. Premium leather combined with a sleek buckle creates a polished, contemporary look.",
    longDescription:
      "Urban Sleek Leather Belt features modern styling, soft premium leather, adjustable sizing, and elegant stitching for urban wear.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/12UrbanSleek-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4112,
    sku: "GG-LB-CM-12",
    leatherFinish: "Textured Finish",
    metaTitle: "Cinch Mark Leather Belt | Stylish Leather Belt",
    metaDescription:
      "Cinch Mark leather belt crafted with premium leather and decorative styling for durable everyday elegance.",
    slug: "cinch-mark-leather-belt",
    relatedProducts: ["GG-LB-CS-13", "GG-LB-SCC-05", "GG-LB-EBR-07"],
    productCode: "GG-LB-CM-12",
    title: "CINCH MARK", // Fixed typo "CNICH"
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Stylish belt with distinctive marking details. Premium leather ensures durability while offering a unique, contemporary design.",
    longDescription:
      "Cinch Mark Leather Belt features high-quality leather, distinctive markings, adjustable sizing, and decorative stitching for style and durability.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/13CinchMark-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4113,
    sku: "GG-LB-CS-13",
    leatherFinish: "Semi-Gloss Finish",
    metaTitle: "Cinnamon Stitched Leather Belt | Decorative Brown Belt",
    metaDescription:
      "Cinnamon Stitched leather belt featuring decorative stitching and premium leather for elegant casual wear.",
    slug: "cinnamon-stitched-leather-belt",
    relatedProducts: ["GG-LB-CBR-04", "GG-LB-SCC-05", "GG-LB-EBR-07"],
    productCode: "GG-LB-CS-13",
    title: "CINNAMON STITCHED",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Elegant brown belt with decorative cinnamon stitching. Perfect for casual and semi-formal attire.",
    longDescription:
      "Cinnamon Stitched Leather Belt combines premium leather with elegant stitching for a stylish and durable everyday belt.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/14CinnamonStitched-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4114,
    sku: "GG-LB-EC-14",
    leatherFinish: "Classic Matte Finish",
    metaTitle: "Eternal Craft Leather Belt | Premium Craftsmanship Belt",
    metaDescription:
      "Eternal Craft leather belt designed for durability, sophistication, and long-lasting everyday comfort.",
    slug: "eternal-craft-leather-belt",
    relatedProducts: ["GG-LB-C06-03", "GG-LB-SB-15", "GG-LB-MID-01"],
    productCode: "GG-LB-EC-14",
    title: "ETERNAL CRAFT",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Premium leather belt crafted for style and longevity. Elegant design perfect for both formal and casual outfits.",
    longDescription:
      "Eternal Craft Leather Belt is designed for long-lasting style, featuring premium leather, elegant stitching, and adjustable fit.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/15Eternal Craft-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4115,
    sku: "GG-LB-SB-15",
    leatherFinish: "Smooth Matte Finish",
    metaTitle: "Sleek Black Leather Belt | Modern Premium Belt",
    metaDescription:
      "Sleek Black leather belt with premium leather, elegant buckle, and minimalist styling for modern outfits.",
    slug: "sleek-black-leather-belt",
    relatedProducts: ["GG-LB-MID-01", "GG-LB-CBL-02", "GG-LB-US-11"],
    productCode: "GG-LB-SB-15",
    title: "SLEEK BLACK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Modern black belt with a sleek buckle design. Premium leather ensures durability and elegance for any outfit.",
    longDescription:
      "Sleek Black Leather Belt is crafted for modern style and comfort, made from premium leather with adjustable sizing and elegant stitching.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/16SleekBlack-Leather-Belt.jpg"],
    moq: 10,
  },
  {
    id: 4116,
    sku: "GG-LB-SL-16",
    leatherFinish: "Polished Finish",
    metaTitle: "Sleek Lock Leather Belt | Auto Lock Premium Belt",
    metaDescription:
      "Sleek Lock leather belt featuring premium leather and modern auto-lock buckle for secure stylish wear.",
    slug: "sleek-lock-leather-belt",
    relatedProducts: ["GG-LB-CL-10", "GG-LB-SB-15", "GG-LB-MID-01"],
    productCode: "GG-LB-SL-16",
    title: "SLEEK LOCK",
    category: "accessories",
    subCat: "leather-belts",
    description:
      "Premium belt with a modern locking buckle. Designed for style, comfort, and long-lasting performance.",
    longDescription:
      "Sleek Lock Leather Belt features a modern locking buckle, premium leather, and elegant stitching for a durable, stylish belt.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "Custom buckle finish",
        "Embossed initials",
        "custom logo engraving",
        "Custom belt length",
        "Custom hole placement",
      ],
      leatherType: "full-grain and top-grain cowhide leather",
      hardwareMaterial: "Stainless Steel (Grade 304)",
      availableSizes: ["30", "32", "34", "36", "38", "40", "42"],
      beltWidth: "35 mm",
      beltThickness: "3.8 mm to 4.0 mm",
      buckleType: "Pin Buckle",
      buckleWidth: "42 mm to 44 mm",
      numberOfHoles: "5 (Standard) or Customizable",
      holePitch: "2.5 cm",
      tipStyle: "English Bridle / Pointed Tip",
      availableColors: ["Black", "Brown", "Tan"],
      unitWeight: "0.18 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Belts/17SleekLock-Leather-Belt.jpg"],
    moq: 10,
  },
  // ------------------- Leather Wallets -------------------
  {
    id: 3101,
    sku: "GG-LW-BIF-COG-01",
    leatherFinish: "Pull-Up Vintage Finish",
    metaTitle: "Bifold Cognac Leather Wallet | Heritage Style Wallet",
    metaDescription:
      "Premium cognac bifold leather wallet crafted from full-grain pull-up leather with hand-burnished edges and rugged vintage character.",
    slug: "bifold-cognac-leather-wallet",
    relatedProducts: [
      "GG-LW-TRV-COG-19",
      "GG-LW-HRT-BRN-21",
      "GG-LW-WRK-MC-26",
    ],
    productCode: "GG-LW-BIF-COG-01",
    title: "BIFOLD COGNAC",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "A rich, warm cognac bifold featuring a distinct marbled grain and rugged character.",
    longDescription:
      "The Bifold Cognac Leather Wallet is crafted from pull-up leather that develops a beautiful patina over time. Its warm reddish-brown hues and visible natural textures make it a standout accessory for those who appreciate heritage styling.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Cognac-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3102,
    sku: "GG-LW-BIF-TAN-02",
    leatherFinish: "Soft Matte Vintage Finish",
    metaTitle: "Bifold Tan Vintage Leather Wallet | Classic Tan Wallet",
    metaDescription:
      "Vintage tan bifold leather wallet featuring premium calfskin leather, slim profile design, and practical everyday storage.",
    slug: "bifold-tan-vintage-leather-wallet",
    relatedProducts: [
      "GG-TW-TRV-TAN-26",
      "GG-LW-WRK-MT-26",
      "GG-LW-JRN-BRN-18",
    ],
    productCode: "GG-LW-BIF-TAN-02",
    title: "BIFOLD TAN VINTAGE",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Lightweight and classic tan leather with a soft matte finish for a modern look.",
    longDescription:
      "This Bifold Tan Leather Wallet features a uniform, honey-colored finish. The interior showcases a traditional layout with symmetrical card slots, offering a balance between slim profile and high storage capacity.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Tan-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3103,
    sku: "GG-LW-BIF-BLU-03",
    leatherFinish: "Semi-Gloss Smooth Finish",
    metaTitle: "Bifold Midnight Blue Leather Wallet | Modern Blue Wallet",
    metaDescription:
      "Sophisticated midnight blue bifold wallet crafted with semi-aniline leather and compact fold technology for professional everyday use.",
    slug: "bifold-midnight-blue-leather-wallet",
    relatedProducts: [
      "GG-LW-JRN-BLK-17",
      "GG-LW-BIF-OXB-04",
      "GG-LW-TRV-BLK-20",
    ],
    productCode: "GG-LW-BIF-BLU-03",
    title: "BIFOLD MIDNIGHT BLUE",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Sophisticated deep blue leather with a smooth, semi-gloss finish.",
    longDescription:
      "Sophisticated midnight blue bifold wallet crafted with semi-aniline leather and compact fold technology for professional everyday use.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Blue-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3104,
    sku: "GG-LW-BIF-OXB-04",
    leatherFinish: "Luxury Smooth Finish",
    metaTitle: "Bifold Oxblood Leather Wallet | Luxury Burgundy Wallet",
    metaDescription:
      "Elegant oxblood bifold leather wallet featuring luxury-grade leather, scratch-resistant finish, and refined wine-red styling.",
    slug: "bifold-oxblood-leather-wallet",
    relatedProducts: [
      "GG-LW-BIF-BLU-03",
      "GG-LW-HRT-BRN-21",
      "GG-LW-WRK-MC-26",
    ],
    productCode: "GG-LW-BIF-OXB-04",
    title: "BIFOLD OXBLOOD",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Bold burgundy tones in a premium smooth-finish leather for a touch of luxury.",
    longDescription:
      "Elegant oxblood bifold leather wallet featuring luxury-grade leather, scratch-resistant finish, and refined wine-red styling.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Oxblood-Leather-Wallet-2.jpg"],
    moq: 10,
  },
  {
    id: 3105,
    sku: "GG-LW-BIF-BRN-05",
    leatherFinish: "Textured Soft Finish",
    metaTitle: "Bifold Brown Leather Wallet with ID Window | Utility Wallet",
    metaDescription:
      "Chocolate brown bifold leather wallet with transparent ID window, textured premium leather, and extra utility compartments.",
    slug: "bifold-brown-id-window-leather-wallet",
    relatedProducts: [
      "GG-LW-JRN-BRN-18",
      "GG-LW-HRT-BRN-22",
      "GG-LW-WRK-MT-26",
    ],
    productCode: "GG-LW-BIF-BRN-05",
    title: "BIFOLD BROWN WITH ID WINDOW",
    category: "accessories",
    subCat: "leather-wallets",
    description:
      "Classic chocolate brown leather featuring a convenient transparent ID window.",
    longDescription:
      "Chocolate brown bifold leather wallet with transparent ID window, textured premium leather, and extra utility compartments.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Brown-Leather-Wallet-2.jpg"],
    moq: 10,
  },

  {
    id: 3201,
    sku: "GG-LW-JRN-BLK-17",
    productCode: "GG-LW-JRN-BLK-17",
    title: "JOURNEYMAN BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Minimal Smooth Finish",
    metaTitle: "Journeyman Black Leather Wallet | Slim Card Holder",
    metaDescription:
      "Minimalist black leather card holder crafted with premium leather and ultra-slim functionality for modern everyday carry.",
    slug: "journeyman-black-leather-wallet",
    description:
      "An ultra-slim, minimalist card holder meticulously crafted from premium black leather, engineered to streamline your daily carry without the bulk.",
    longDescription:
      "The Journeyman Black Leather Wallet is the ultimate expression of modern minimalism. Crafted from premium top-tier cowhide leather with a sleek, minimal smooth finish, this compact card holder fits seamlessly into front pockets. Designed for individuals who prioritize efficiency, it securely houses your most essential cards while maintaining an incredibly low profile. Hand-burnished edges and reinforced stitching ensure long-term structural integrity for everyday use.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Journeyman-Black-Leather-Wallet.jpg"],
    relatedProducts: [
      "GG-LW-TRV-BLK-20",
      "GG-LW-BIF-BLU-03",
      "GG-SW-TRI-BLK-26",
    ],
    moq: 10,
  },
  {
    id: 3202,
    sku: "GG-LW-JRN-BRN-18",
    productCode: "GG-LW-JRN-BRN-18",
    title: "JOURNEYMAN BROWN",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Classic Matte Finish",
    metaTitle: "Journeyman Brown Leather Wallet | Slim Leather Card Holder",
    metaDescription:
      "Elegant brown slim card holder crafted with genuine leather and compact functionality for daily essentials.",
    slug: "journeyman-brown-leather-wallet",
    description:
      "A classic, heritage-toned slim card holder built from rich brown premium leather, offering an elegant profile for streamlined storage.",
    longDescription:
      "Combining traditional style with contemporary functionality, the Journeyman Brown Leather Wallet offers an elegant, slim-line silhouette. The classic matte finish accentuates the natural character of premium cowhide leather, developing a unique patina over time. Perfect for consolidating cards and folded bills, its compact engineering makes it unnoticeable in your tailored trousers or jacket pocket. Finished with reinforced edge stitching for enhanced durability.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Journeyman-Brown-Leather-Wallet.jpg"],
    relatedProducts: [
      "GG-LW-BIF-TAN-02",
      "GG-LW-BIF-BRN-05",
      "GG-LW-HRT-BRN-22",
    ],
    moq: 10,
  },
  {
    id: 3203,
    sku: "GG-LW-TRV-COG-19",
    productCode: "GG-LW-TRV-COG-19",
    title: "TRAVELMAN COGNAC",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Vintage Pull-Up Finish",
    metaTitle: "TravelMan Cognac Leather Wallet | Vertical Bifold Wallet",
    metaDescription:
      "Sophisticated cognac vertical bifold wallet crafted with premium leather and compact travel-ready storage compartments.",
    slug: "travelman-cognac-leather-wallet",
    description:
      "A sophisticated, high-character vertical bifold wallet crafted from rich cognac leather with a distinctive vintage pull-up effect.",
    longDescription:
      "Engineered for modern travelers and commuters, the TravelMan Cognac Leather Wallet offers an optimized vertical bifold structure. The premium pull-up leather displays a beautiful burst of lighter tones when flexed, highlighting its authentic, rugged character. Its tailored interior safely organizes currency and credit cards vertically, allowing quick accessibility while maintaining a slim footprint that keeps your transit items organized.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Cognac-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-BIF-COG-01",
      "GG-LW-WRK-MC-26",
      "GG-LW-HRT-BRN-21",
    ],
    moq: 10,
  },
  {
    id: 3204,
    sku: "GG-LW-TRV-BLK-20",
    productCode: "GG-LW-TRV-BLK-20",
    title: "TRAVELMAN BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Professional Smooth Finish",
    metaTitle: "TravelMan Black Leather Wallet | Vertical Travel Wallet",
    metaDescription:
      "Professional black vertical bifold leather wallet with premium finish and organized travel-friendly compartments.",
    slug: "travelman-black-leather-wallet",
    description:
      "A sleek, professional vertical bifold wallet meticulously crafted from polished black premium leather for the discerning executive.",
    longDescription:
      "The TravelMan Black Leather Wallet balances professional corporate aesthetics with practical, high-capacity utility. Featuring a sharp vertical orientation, this bifold wallet smoothly slides into breast pockets or deep pockets without distorting your clothing's lines. The professional smooth finish offers an upscale feel, while the hand-finished edges and heavy-duty lining secure your financial essentials wherever your business trips take you.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Black-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-JRN-BLK-17",
      "GG-SW-TRI-BLK-26",
      "GG-LW-BIF-BLU-03",
    ],
    moq: 10,
  },
  {
    id: 3205,
    sku: "GG-LW-HRT-BRN-21",
    productCode: "GG-LW-HRT-BRN-21",
    title: "HERITAGE LONG WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Vintage Pull-Up Finish",
    metaTitle: "Heritage Long Leather Wallet | Vintage Chain Wallet",
    metaDescription:
      "Rugged heritage long wallet crafted from heavy-duty pull-up leather with chain-ready vintage biker styling.",
    slug: "heritage-long-leather-wallet",
    description:
      "A heavy-duty, vintage-inspired long leather wallet designed with an authentic biker silhouette and an integrated security chain grommet.",
    longDescription:
      "Built for open roads and rugged lifestyles, the Heritage Long Leather Wallet is built from substantial, thick pull-up cowhide leather. This high-capacity checkbook-style wallet features expansive cash panels and a secure internal layout to keep vital documents flat. It includes a built-in lanyard grommet, allowing it to easily clip to a traditional security chain. The vintage pull-up surface quickly develops unique highlights, building a rugged personalized look with extensive handling.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Heritage-Long-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-HRT-BRN-22",
      "GG-LW-WRK-MC-26",
      "GG-LW-BIF-COG-01",
    ],
    moq: 10,
  },
  {
    id: 3206,
    sku: "GG-LW-HRT-BRN-22",
    productCode: "GG-LW-HRT-BRN-22",
    title: "HERITAGE LONG WALLET BROWN",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Distressed Vintage Finish",
    metaTitle: "Heritage Long Wallet Brown | Rugged Leather Wallet",
    metaDescription:
      "Brown heritage long leather wallet featuring rugged vintage aesthetics and durable pull-up leather craftsmanship.",
    slug: "heritage-long-wallet-brown",
    description:
      "A deeply textured, distressed brown long wallet detailed with classic western styling and an integrated security lanyard attachment.",
    longDescription:
      "The Heritage Long Wallet Brown delivers immediate vintage appeal with its beautiful distressed surface texture. The rich, deep brown tone displays deliberate variations in the grain, giving it a classic, broken-in look right out of the box. Engineered to hold full-sized bills without folding, this durable trucker-style wallet relies on a multi-layered structure and dense reinforced stitching to resist wearing down, making it perfect for heavy-duty daily carry.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Heritage-Long-Brown-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-HRT-BRN-21",
      "GG-LW-WRK-MT-26",
      "GG-LW-BIF-BRN-05",
    ],
    moq: 10,
  },
  {
    id: 3208,
    sku: "GG-SW-TRI-BLK-26",
    productCode: "GG-SW-TRI-BLK-26",
    title: "CLASSIC LEATHER TRIFOLD WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Smooth Refined Finish",
    metaTitle: "Classic Leather Trifold Wallet | Black Trifold Wallet",
    metaDescription:
      "Compact black trifold leather wallet with smooth genuine leather finish, ID window, and practical everyday organization.",
    slug: "classic-leather-trifold-wallet",
    description:
      "A compact, traditionally designed trifold wallet engineered from smooth black leather with elegant contrast perimeter stitching.",
    longDescription:
      "For those who prefer a classic layout, the Classic Leather Trifold Wallet provides exceptional compartmentalization inside a compact frame. It features a sophisticated smooth finish that feels soft in hand while resisting daily pocket friction. Designed with multiple tiered card sectors and a clear view frame for identification, it maximizes internal efficiency without creating bulk when folded shut. Perfect for anchoring an organized everyday carry.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Trifold-Black-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-TRV-BLK-20",
      "GG-LW-JRN-BLK-17",
      "GG-LW-WRK-MB-26",
    ],
    moq: 20,
  },
  {
    id: 3209,
    sku: "GG-TW-TRV-TAN-26",
    productCode: "GG-TW-TRV-TAN-26",
    title: "TRAVELMAN PASSPORT WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Premium Matte Finish",
    metaTitle: "TravelMan Passport Wallet | Tan Travel Leather Wallet",
    metaDescription:
      "Slim tan passport wallet crafted with premium leather and vertical travel compartments for organized journeys.",
    slug: "travelman-passport-wallet",
    description:
      "A slim, vertical travel companion specifically designed to secure passports, boarding passes, and currency in refined matte tan leather.",
    longDescription:
      "Streamline your international airport navigation with the TravelMan Passport Wallet. Moving away from heavy, over-sized travel organizers, this specialized sleek passport sleeve fits effortlessly into jacket pockets. It features dedicated fast-access card slots for your primary credit cards and travel IDs alongside a reinforced main passport pocket. The premium matte finish provides an excellent tactile grip, ensuring your critical documents stay safe and organized throughout your journey.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/TravelMan-Tan-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-BIF-TAN-02",
      "GG-LW-JRN-BRN-18",
      "GG-LW-WRK-MT-26",
    ],
    moq: 15,
  },
  {
    id: 3210,
    sku: "GG-LW-WRK-MB-26",
    productCode: "GG-LW-WRK-MB-26",
    title: "WORKMAN LONG WALLET BLACK",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Vegetable Tanned Matte Finish",
    metaTitle: "Workman Long Wallet Black | Biker Leather Wallet",
    metaDescription:
      "Robust black biker long wallet crafted from full-grain vegetable-tanned leather with snap closures and chain-ready design.",
    slug: "workman-long-wallet-black",
    description:
      "A robust, high-capacity utility long wallet built from matte black vegetable-tanned leather, complete with dual hardware snaps.",
    longDescription:
      "The Workman Long Wallet Black is a masterclass in industrial utility and structural durability. Handcrafted from heavy vegetable-tanned cowhide, it features a distinctive angular front flap backed by dual heavy-gauge snap closures to lock down your contents. Equipped with an integrated reinforced metal lanyard grommet for tethering wallet chains, this robust long wallet easily stores bills flat, holds multiple receipts, and resists stretching under intense everyday use.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Tan",
        "Cognac",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Workman-Black-Leather-Wallet-1.jpg"],
    relatedProducts: ["GG-LW-WRK-MC-26", "GG-LW-WRK-MT-26", "GG-SW-TRI-BLK-26"],
    moq: 10,
  },
  {
    id: 3211,
    sku: "GG-LW-WRK-MC-26",
    productCode: "GG-LW-WRK-MC-26",
    title: "WORKMAN LONG WALLET Cognac",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Vintage Vegetable Tanned Finish",
    metaTitle: "Workman Long Wallet Cognac | Rugged Biker Wallet",
    metaDescription:
      "Cognac long biker wallet crafted from full-grain vegetable-tanned leather with durable utility-focused construction.",
    slug: "workman-long-wallet-cognac",
    description:
      "A striking utility long wallet rendered in warm cognac vegetable-tanned leather, highlighted by an angular front flap and dual secure closure snaps.",
    longDescription:
      "Enriched with a classic vintage vegetable-tanned finish, the Workman Long Wallet Cognac combines heavy-duty security with high-end aesthetic warmth. The deep amber-cognac hue naturally darkens over time, recording a custom heritage appearance based on how it is handled. Its long, un-folded layout provides abundant space for cash, checks, and passports, while a solid structural steel grommet offers secure attachment points for anti-theft pocket lanyards.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Cognac",
        "Tan",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Workman-Cognac-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-WRK-MB-26",
      "GG-LW-BIF-COG-01",
      "GG-LW-HRT-BRN-21",
    ],
    moq: 10,
  },
  {
    id: 3212,
    sku: "GG-LW-WRK-MT-26",
    productCode: "GG-LW-WRK-MT-26",
    title: "WORKMAN LONG WALLET",
    category: "accessories",
    subCat: "leather-wallets",
    leatherFinish: "Distressed Matte Finish",
    metaTitle: "Workman Long Wallet Tan | Premium Leather Biker Wallet",
    metaDescription:
      "Tan long biker wallet made from full-grain vegetable-tanned leather with high-capacity compartments and rugged styling.",
    slug: "workman-long-wallet-tan",
    description:
      "A rugged, classic tan long utility wallet detailed with a distressed matte finish, secure dual snaps, and built-in chain lanyard attachment.",
    longDescription:
      "The Workman Long Wallet Tan delivers an authentic, time-worn aesthetic right from day one. Made from full-grain vegetable-tanned cowhide with a textured distressed matte finish, it is engineered to handle friction and rugged handling. The high-capacity interior safely isolates cards and un-folded currencies into structured tiers, keeping your financial items secured with dual reinforced metallic snaps.",
    specifications: {
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "RFID protection upgrade",
        "Custom Colors",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Open Fold / Snap Closure (Model Dependent)",
      cardSlotCapacity: "4 to 12 Cards",
      rfidBlocking: "Optional / Customizable",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Polyester Twill or Leather Lining",
      availableColors: [
        "Black",
        "Cognac",
        "Tan",
        "Navy",
        "Oxblood",
        "Green",
        "custom colors available",
      ],
      unitWeight: "0.10 kg to 0.28 kg",
    },
    imageUrl: ["/Leather-Wallets/Workman-Tan-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-LW-WRK-MB-26",
      "GG-TW-TRV-TAN-26",
      "GG-LW-HRT-BRN-22",
    ],
    moq: 10,
  },
  // ------------------- RFID Blocking Wallets -------------------
  {
    id: 3301,
    sku: "GG-RFID-SBF-BLK-01",
    productCode: "GG-RFID-SBF-BLK-01",
    title: "RFID SLIM BIFOLD BLACK",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Smooth Matte Finish",
    metaTitle: "RFID Slim Bifold Black Leather Wallet | Secure Wallet",
    metaDescription:
      "Slim black RFID blocking leather bifold wallet with protected card storage, premium stitching, and custom branding options.",
    slug: "rfid-slim-bifold-black-leather-wallet",
    description:
      "A slim black leather bifold wallet built with RFID blocking lining for secure everyday card carry.",
    longDescription:
      "The RFID Slim Bifold Black wallet combines a clean professional profile with integrated RFID blocking material to help protect contactless cards during daily travel. Crafted from full-grain and top-grain cowhide leather, it features reinforced edge stitching, hand-finished edges, a compact cash section, and practical card slots designed for buyers who need dependable private-label wallet production.",
    specifications: {
      leadTimeDays: 12,
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom interior lining",
        "Custom RFID blocking layer",
        "Custom packaging",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.2 cm to 2.0 cm",
      walletClosureType: "Open Fold",
      cardSlotCapacity: "6 to 10 Cards",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "RFID Shield Fabric with Soft Polyester Twill",
      availableColors: ["Black", "Brown", "Cognac", "Tan", "Navy"],
      unitWeight: "0.10 kg to 0.20 kg",
    },
    imageUrl: ["/Leather-Wallets/Journeyman-Black-Leather-Wallet.jpg"],
    relatedProducts: [
      "GG-RFID-CCH-COG-02",
      "GG-RFID-TMC-TAN-03",
      "GG-RFID-OTF-OXB-04",
    ],
    moq: 25,
  },
  {
    id: 3302,
    sku: "GG-RFID-CCH-COG-02",
    productCode: "GG-RFID-CCH-COG-02",
    title: "RFID COGNAC CARD HOLDER",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Pull-Up Cognac Finish",
    metaTitle: "RFID Cognac Leather Card Holder | Minimal Secure Wallet",
    metaDescription:
      "Compact cognac RFID blocking leather card holder with front pocket profile, premium pull-up leather, and export-ready construction.",
    slug: "rfid-cognac-leather-card-holder",
    description:
      "A compact cognac leather card holder with RFID blocking protection and a slim front-pocket profile.",
    longDescription:
      "The RFID Cognac Card Holder is designed for minimalist daily carry while maintaining a premium handmade feel. Its pull-up leather surface develops a rich patina over time, while the internal RFID blocking layer helps protect contactless cards. The compact layout supports essential cards and folded currency without excess bulk, making it ideal for custom branding and wholesale accessory programs.",
    specifications: {
      leadTimeDays: 12,
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Custom card slot layout",
        "Custom RFID blocking layer",
        "Custom Colors",
      ],
      leatherType: "Full-Grain Pull-Up Cowhide Leather",
      walletThickness: "0.8 cm to 1.5 cm",
      walletClosureType: "Open Card Holder",
      cardSlotCapacity: "4 to 8 Cards",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Compact Reinforced Stitching",
      edgeFinish: "Burnished Edges",
      liningMaterial: "RFID Shield Fabric",
      availableColors: ["Cognac", "Black", "Brown", "Tan", "Oxblood"],
      unitWeight: "0.06 kg to 0.14 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Cognac-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-RFID-SBF-BLK-01",
      "GG-RFID-TMC-TAN-03",
      "GG-RFID-NPW-NAV-05",
    ],
    moq: 25,
  },
  {
    id: 3303,
    sku: "GG-RFID-TMC-TAN-03",
    productCode: "GG-RFID-TMC-TAN-03",
    title: "RFID TAN MONEY CLIP WALLET",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Soft Matte Tan Finish",
    metaTitle: "RFID Tan Money Clip Leather Wallet | Slim Cash Wallet",
    metaDescription:
      "Tan RFID blocking leather money clip wallet with slim cash carry, card slots, and customizable private-label options.",
    slug: "rfid-tan-money-clip-leather-wallet",
    description:
      "A tan leather RFID money clip wallet made for slim cash carry and organized card access.",
    longDescription:
      "The RFID Tan Money Clip Wallet offers a clean, slim alternative to traditional bifolds. Built with RFID blocking lining and a secure money clip layout, it keeps key cards and folded bills organized without heavy pocket bulk. The soft matte tan finish gives the wallet a warm retail-ready appearance, while the construction supports logo embossing, custom lining, and private-label packaging.",
    specifications: {
      leadTimeDays: 12,
      customizationOptions: [
        "Custom money clip finish",
        "Embossed initials",
        "Custom logo engraving",
        "Custom RFID blocking layer",
        "Custom packaging",
      ],
      leatherType: "Top-Grain Cowhide Leather",
      walletThickness: "0.9 cm to 1.6 cm",
      walletClosureType: "Money Clip",
      cardSlotCapacity: "4 to 8 Cards",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted Edges",
      liningMaterial: "RFID Shield Fabric with Twill Backing",
      availableColors: ["Tan", "Black", "Brown", "Cognac"],
      unitWeight: "0.08 kg to 0.16 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Tan-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-RFID-CCH-COG-02",
      "GG-RFID-SBF-BLK-01",
      "GG-RFID-GZW-GRN-06",
    ],
    moq: 25,
  },
  {
    id: 3304,
    sku: "GG-RFID-OTF-OXB-04",
    productCode: "GG-RFID-OTF-OXB-04",
    title: "RFID OXBLOOD TRIFOLD",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Refined Oxblood Finish",
    metaTitle: "RFID Oxblood Trifold Leather Wallet | Secure Trifold",
    metaDescription:
      "Oxblood RFID blocking leather trifold wallet with high card capacity, refined finish, and durable export-grade stitching.",
    slug: "rfid-oxblood-trifold-leather-wallet",
    description:
      "A refined oxblood leather trifold wallet with RFID protection and expanded card organization.",
    longDescription:
      "The RFID Oxblood Trifold is made for customers who want compact folded dimensions with higher internal capacity. The RFID blocking lining supports secure contactless card storage, while the trifold layout provides organized access to cards, cash, receipts, and ID sections. Its wine-red oxblood leather finish, reinforced seams, and hand-finished edges give it a polished premium look for retail and private-label collections.",
    specifications: {
      leadTimeDays: 14,
      customizationOptions: [
        "Custom card slot layout",
        "Embossed initials",
        "Custom logo engraving",
        "ID window option",
        "Custom RFID blocking layer",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      walletThickness: "1.6 cm to 2.6 cm",
      walletClosureType: "Trifold Open Fold",
      cardSlotCapacity: "8 to 14 Cards",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "RFID Shield Fabric with Soft Polyester Twill",
      availableColors: ["Oxblood", "Black", "Brown", "Navy"],
      unitWeight: "0.12 kg to 0.24 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Oxblood-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-RFID-SBF-BLK-01",
      "GG-RFID-NPW-NAV-05",
      "GG-RFID-GZW-GRN-06",
    ],
    moq: 25,
  },
  {
    id: 3305,
    sku: "GG-RFID-NPW-NAV-05",
    productCode: "GG-RFID-NPW-NAV-05",
    title: "RFID NAVY PASSPORT WALLET",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Semi-Aniline Navy Finish",
    metaTitle: "RFID Navy Passport Leather Wallet | Travel Document Wallet",
    metaDescription:
      "Navy RFID blocking passport leather wallet for travel documents, cards, currency, and custom wholesale production.",
    slug: "rfid-navy-passport-leather-wallet",
    description:
      "A navy leather RFID passport wallet designed for secure travel documents, cards, and currency.",
    longDescription:
      "The RFID Navy Passport Wallet is a travel-focused leather accessory with dedicated space for passports, cards, folded boarding passes, and currency. Its RFID blocking lining helps protect contactless cards during transit, while the vertical profile keeps documents organized and easy to access. The semi-aniline navy finish gives it a modern executive look suited for travel brands, corporate gifting, and custom private-label programs.",
    specifications: {
      leadTimeDays: 14,
      customizationOptions: [
        "Embossed initials",
        "Custom logo engraving",
        "Passport pocket layout",
        "Custom RFID blocking layer",
        "Gift box packaging",
      ],
      leatherType: "Semi-Aniline Top-Grain Cowhide Leather",
      walletThickness: "1.2 cm to 2.2 cm",
      walletClosureType: "Open Fold / Snap Closure Option",
      cardSlotCapacity: "4 to 10 Cards plus Passport Pocket",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Reinforced Travel Stitching",
      edgeFinish: "Hand-Painted Edges",
      liningMaterial: "RFID Shield Fabric with Soft Twill Lining",
      availableColors: ["Navy", "Black", "Cognac", "Tan", "Green"],
      unitWeight: "0.12 kg to 0.22 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Blue-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-RFID-CCH-COG-02",
      "GG-RFID-OTF-OXB-04",
      "GG-RFID-GZW-GRN-06",
    ],
    moq: 20,
  },
  {
    id: 3306,
    sku: "GG-RFID-GZW-GRN-06",
    productCode: "GG-RFID-GZW-GRN-06",
    title: "RFID GREEN ZIP WALLET",
    category: "accessories",
    subCat: "rfid-blocking-wallets",
    leatherFinish: "Soft Pebbled Green Finish",
    metaTitle: "RFID Green Zip Leather Wallet | Secure Zip Wallet",
    metaDescription:
      "Green RFID blocking zip leather wallet with secure zipper closure, card organization, and custom leather production options.",
    slug: "rfid-green-zip-leather-wallet",
    description:
      "A secure green leather RFID zip wallet with compact storage for cards, cash, and daily essentials.",
    longDescription:
      "The RFID Green Zip Wallet adds zipper security to a compact leather wallet profile. Made with soft pebbled leather and an integrated RFID blocking layer, it is designed to protect cards while keeping cash and small essentials contained. The zip-around construction, reinforced stitching, and custom color options make it a strong fit for boutique accessory ranges and wholesale leather wallet programs.",
    specifications: {
      leadTimeDays: 14,
      customizationOptions: [
        "Custom zipper finish",
        "Embossed initials",
        "Custom logo engraving",
        "Custom RFID blocking layer",
        "Custom Colors",
      ],
      leatherType: "Pebbled Top-Grain Cowhide Leather",
      walletThickness: "1.5 cm to 2.5 cm",
      walletClosureType: "Zip-Around Closure",
      cardSlotCapacity: "6 to 12 Cards",
      rfidBlocking: "Integrated RFID Blocking Lining",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted Edges",
      liningMaterial: "RFID Shield Fabric with Soft Polyester Twill",
      availableColors: ["Green", "Black", "Navy", "Cognac", "Oxblood"],
      unitWeight: "0.14 kg to 0.26 kg",
    },
    imageUrl: ["/Leather-Wallets/Bifold-Brown-Leather-Wallet-2.jpg"],
    relatedProducts: [
      "GG-RFID-TMC-TAN-03",
      "GG-RFID-OTF-OXB-04",
      "GG-RFID-NPW-NAV-05",
    ],
    moq: 20,
  },
];

export default ACCESSORIES;
