const apparel = [
  {
    id: 5001,
    sku: "LJ-BR-HUB-01",
    leatherFinish: "Genuine Leather",
    metaTitle: "HOODED UTILITY BOMBER Premium Leather Jacket",
    metaDescription:
      "Versatile hybrid bomber with integrated hoodie and utility chest pockets designed for modern streetwear functionality.",
    slug: "hooded-utility-bomber",
    relatedProducts: [5003, 5012],
    productCode: "LJ-BR-HUB-01",
    title: "HOODED UTILITY BOMBER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A versatile hybrid jacket featuring a straight front zipper and dual button-flap chest pockets.",
    longDescription:
      "The Hooded Utility Bomber combines classic leather craftsmanship with modern streetwear, featuring an integrated grey fabric hoodie for a layered look without the bulk.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Premium Full-Grain and Top-Grain Cowhide Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Black", "Classic Brown", "Tan", "custom color"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/hooded-utility-bomber.jpg"],
    moq: 5,
  },
  {
    id: 5002,
    Sku: "LJ-ES-MBC-02",
    leatherFinish: "Full-Grain Leather",
    metaTitle: "MODERN BIKER WITH CONTRAST STITCHING Premium Leather Jacket",
    metaDescription:
      "Espresso biker jacket with asymmetric zip and signature contrast stitching for a bold designer finish.",
    slug: "modern-biker-with-contrast-stitching",
    relatedProducts: [5008, 5009],
    productCode: "LJ-ES-MBC-02",
    title: "MODERN BIKER WITH CONTRAST STITCHING",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "An espresso-toned asymmetric jacket featuring unique orange/tan contrast stitching.",
    longDescription:
      "This modern take on the biker jacket uses espresso leather and high-contrast stitching to highlight the iconic notched collar and asymmetric zip silhouette.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Full-Grain Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Espresso", "Tan"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/modern-biker-with-contrast-stitching.jpg"],
    moq: 5,
  },
  {
    id: 5003,
    sku: "LJ-BK-MPC-03",
    leatherFinish: "Smooth Leather",
    metaTitle: "MULTI-POCKET COMMUTER JACKET Premium Leather Jacket",
    metaDescription:
      "Utility-focused black leather commuter jacket with multiple zip compartments and ribbed hem for urban use.",
    slug: "multi-pocket-commuter-jacket",
    relatedProducts: [5001, 5012],
    productCode: "LJ-BK-MPC-03",
    title: "MULTI-POCKET COMMUTER JACKET",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A black hybrid jacket with a fabric hood, ribbed hem, and functional utility zippers.",
    longDescription:
      "Designed for the urban explorer, the Multi-Pocket Commuter features several secure zip compartments and a comfortable ribbed waist for all-day wear.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Smooth Black Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Black"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/multi-pocket-commuter-jacket.jpg"],
    moq: 5,
  },
  {
    id: 5004,
    Sku: "LJ-BR-SLA-04",
    leatherFinish: "Distressed Leather",
    metaTitle: "SHERPA-LINED AVIATOR JACKET Premium Leather Jacket",
    metaDescription:
      "Heavy-duty aviator jacket with sherpa lining and shearling collar designed for maximum winter insulation.",
    slug: "sherpa-lined-aviator-jacket",
    relatedProducts: [5005, 5007],
    productCode: "LJ-BR-SLA-04",
    title: "SHERPA-LINED AVIATOR JACKET",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "Rugged brown leather paired with a thick, cream-colored shearling collar and trim.",
    longDescription:
      "The Sherpa-Lined Aviator is built for extreme warmth and durability, referencing WWII flight jacket designs with heavy-duty insulation.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Distressed Brown Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Brown", "Cream"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/sherpa-lined-aviator-jacket.jpg"],
    moq: 5,
  },
  {
    id: 5005,
    Sku: "LJ-BR-TLB-05",
    leatherFinish: "Polished Lambskin",
    metaTitle: "TAILORED LEATHER BLAZER Premium Leather Jacket",
    metaDescription:
      "Refined leather blazer combining formal tailoring with luxury leather craftsmanship for versatile styling.",
    slug: "tailored-leather-blazer",
    relatedProducts: [5010, 5008],
    productCode: "LJ-BR-TLB-05",
    title: "TAILORED LEATHER BLAZER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A sophisticated, two-button leather sport coat with a traditional notched lapel.",
    longDescription:
      "Elevate your professional wardrobe with the Tailored Leather Blazer, combining the structure of a suit with the luxury of fine leather.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Polished Lambskin",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Chocolate Brown"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/tailored-leather-blazer.jpg"],
    moq: 5,
  },
  {
    id: 5006,
    Sku: "LJ-BR-VCR-06",
    leatherFinish: "Aged Leather",
    metaTitle: "VINTAGE CAFE RACER Premium Leather Jacket",
    metaDescription:
      "Slim vintage racer jacket inspired by 1960s motorcycle culture with minimalist detailing and distressed finish.",
    slug: "vintage-cafe-racer",
    relatedProducts: [5007, 5009],
    productCode: "LJ-BR-VCR-06",
    title: "VINTAGE CAFE RACER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A minimalist, distressed brown leather jacket featuring a snap-tab band collar.",
    longDescription:
      "The Vintage Cafe Racer celebrates 1960s motorcycle culture with a sleek, aerodynamic design and subtle shoulder quilting.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Aged Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Vintage Brown"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/vintage-cafe-racer.jpg"],
    moq: 5,
  },
  {
    id: 5007,
    Sku: "LJ-BR-DHB-07",
    leatherFinish: "Cowhide Leather",
    metaTitle: "DISTRESSED HERITAGE BIKER Premium Leather Jacket",
    metaDescription:
      "Classic heritage biker jacket with weathered leather, asymmetric zip, and antique brass hardware.",
    slug: "distressed-heritage-biker",
    relatedProducts: [5009, 5002],
    productCode: "LJ-BR-DHB-07",
    title: "DISTRESSED HERITAGE BIKER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A classic double-rider silhouette in weathered leather with an asymmetric zipper and belt.",
    longDescription:
      "Embody the golden age of motorcycle style with the Heritage Biker, featuring a pre-weathered look and heavy-duty hardware.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Cowhide Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Distressed Tan"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/distressed-heritage-biker.jpg"],
    moq: 5,
  },
  {
    id: 5008,
    Sku: "LJ-BR-CLM-08",
    leatherFinish: "Smooth Leather",
    metaTitle: "CHOCOLATE LEATHER MOTO Premium Leather Jacket",
    metaDescription:
      "Slim-fit chocolate brown moto jacket with silver hardware and asymmetric biker styling.",
    slug: "chocolate-leather-moto",
    relatedProducts: [5002, 5009],
    productCode: "LJ-BR-CLM-08",
    title: "CHOCOLATE LEATHER MOTO",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A clean-cut, dark brown biker jacket with silver hardware and an asymmetric zip.",
    longDescription:
      "The Chocolate Leather Moto offers a refined take on the biker jacket, using smooth, dark leather for a more versatile, upscale appearance.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Premium Smooth Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Chocolate Brown"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/chocolate-leather-moto.jpg"],
    moq: 5,
  },
  {
    id: 5009,
    Sku: "LJ-BK-CBD-09",
    leatherFinish: "Heavyweight Leather",
    metaTitle: "CLASSIC BLACK DOUBLE RIDER Premium Leather Jacket",
    metaDescription:
      "Iconic black double rider jacket featuring waist belt, asymmetric zip, and snap lapels.",
    slug: "classic-black-double-rider",
    relatedProducts: [5007, 5008],
    productCode: "LJ-BK-CBD-09",
    title: "CLASSIC BLACK DOUBLE RIDER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "The quintessential 'rockstar' jacket with an asymmetric zip and lapel snaps.",
    longDescription:
      "This is the definitive black leather jacket, featuring a full waist belt and lapels that snap down for a timeless, aggressive profile.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Heavyweight Black Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Black"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/classic-black-double-rider.png"],
    moq: 5,
  },
  {
    id: 5010,
    Sku: "LJ-BK-PLF-10",
    leatherFinish: "Nappa Leather",
    metaTitle: "POLISHED LEATHER FIELD JACKET Premium Leather Jacket",
    metaDescription:
      "Minimalist black leather field jacket with clean structure and professional finish.",
    slug: "polished-leather-field-jacket",
    relatedProducts: [5003, 5012],
    productCode: "LJ-BK-PLF-10",
    title: "POLISHED LEATHER FIELD JACKET",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A minimalist black jacket with a clean fold-over collar and a straight-zip front.",
    longDescription:
      "The Polished Field Jacket offers a sophisticated, understated look that works perfectly over business attire or casual wear.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Nappa Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Matte Black"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/polished-leather-field-jacket.jpg"],
    moq: 5,
  },
  {
    id: 5011,
    Sku: "LJ-BK-QBJ-11",
    leatherFinish: "Flexible Leather",
    metaTitle: "QUILTED BIKER JACKET Premium Leather Jacket",
    metaDescription:
      "Athletic slim-fit biker jacket with accordion quilting and enhanced mobility design.",
    slug: "quilted-biker-jacket",
    relatedProducts: [5009, 5002],
    productCode: "LJ-BK-QBJ-11",
    title: "QUILTED BIKER JACKET",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A slim-fit black moto jacket featuring prominent 'accordion' quilting on the shoulders.",
    longDescription:
      "The Quilted Biker combines high-fashion textures with athletic inspiration, featuring accordion stretch panels on the sleeves for maximum mobility.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Flexible Black Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Deep Black"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/quilted-biker-jacket.png"],
    moq: 5,
  },
  {
    id: 5012,
    Sku: "LJ-BK-EBB-12",
    leatherFinish: "Premium Calfskin",
    metaTitle: "ELITE LEATHER BOMBER Premium Leather Jacket",
    metaDescription:
      "Luxury MA-1 bomber jacket with ribbed trims and premium leather finish for everyday wear.",
    slug: "elite-leather-bomber",
    relatedProducts: [5001, 5010],
    productCode: "LJ-BK-EBB-12",
    title: "ELITE LEATHER BOMBER",
    category: "apparel",
    subCat: "leather-jackets",
    description:
      "A sleek, black MA-1 style bomber with a ribbed collar, cuffs, and hem.",
    longDescription:
      "The Elite Leather Bomber is the ultimate luxury staple, featuring premium leather and a sporty silhouette that fits any wardrobe.",
    specifications: {
      leadTimeDays: 15,
      leatherType: "Premium Full-Grain and Top-Grain Cowhide Leather",
      availableSizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
      availableColors: ["Black", "Classic Brown", "Tan", "custom color"],
      customizationOptions: [
        "Custom lining material (Satin/Silk/Thinsulate)",
        "Embossed initials or custom brand logo",
        "Hardware finish hardware (Silver, Gunmetal, Antique Brass)",
        "Made-to-measure sizing (Sleeve and back length adjustment)",
        "Removable hood or collar attachment",
      ],
      unitWeight: "1.5 kg to 2.5 kg",
    },
    imageUrl: ["/Leather-Jackets/elite-leather-bomber.jpg"],
    moq: 5,
  },

  // leather chaps
  {
      id: 6010,
      Sku: "WC-BR-CST-10",
      leatherFinish: "Oil-Tanned Leather",
      metaTitle: "Custom Western Leather Chaps | Personalized Cowboy Gear",
      metaDescription:
        "Handcrafted in the USA from lightweight oil-tanned leather. Features personalized yokes, adjustable laced fit, and traditional fringe.",
      slug: "custom-western-leather-chaps",
      relatedProducts: [5012, 5013],
      productCode: "WC-BR-CST-10",
      title: "Custom Western Leather Chaps",
      category: "apparel",
      subCat: "cowboy-chaps",
      description:
        "Lightweight chrome oil tanned leather cowboy chaps with a soft, broken-in feel and classic fringe styling.",
      longDescription:
        "Designed for comfort, protection, and classic western style, these leather fringe cowboy chaps are built for men and women who spend long days riding or working on the ranch. Handcrafted in the USA, they feature durable stainless steel buckles, solid brass YKK® zippers, and an adjustable laced leg design for a personalized fit.",
      specifications: {
        leadTimeDays: 20,
        leatherType: "2–3 oz. Chrome Oil Tanned Leather",
        availableSizes: ["S", "M", "L", "XL", "Custom"],
        availableColors: ["Chocolate", "Brandy"],
        customizationOptions: [
          "Personalized yokes (initials or brand logo)",
          "Personalized legs (initials or brand logo)",
          "Custom laced leg circumference adjustment",
        ],
        unitWeight: "1.2 kg to 2.0 kg",
      },
      imageUrl: [
        "/cowboy-chaps/custom-western-leather-chaps-1.png",
        "/cowboy-chaps/custom-western-leather-chaps-2.webp",
        "/cowboy-chaps/custom-western-leather-chaps-3.webp",
      ],
      moq: 1,
    },
    {
      id: 5011,
      Sku: "HC-BR-STD-11",
      leatherFinish: "Top Grain Leather",
      metaTitle: "Leather Hay Chap | Protective Work Chops",
      metaDescription:
        "Durable brown top grain leather hay chaps handmade by Weaver Equine. Short, flexible design with snap-on leg straps.",
      slug: "leather-hay-chap",
      relatedProducts: [5010, 5013],
      productCode: "HC-BR-STD-11",
      title: "Leather Hay Chap",
      category: "apparel",
      subCat: "cowboy-chaps",
      description:
        "Practical top grain leather protective chaps designed for everyday barn chores and handling hay bales.",
      longDescription:
        "Designed for everyday barn and ranch chores, these leather hay chaps offer practical protection when handling hay bales. Made from durable brown top grain leather, the shorter length allows easy movement while shielding your legs from prickles, pokes, and abrasion. They snap securely around each leg for a stable fit.",
      specifications: {
        leadTimeDays: 10,
        leatherType: "Brown Top Grain Leather",
        availableSizes: ["Standard", "Adjustable"],
        availableColors: ["Brown"],
        customizationOptions: ["Adjustable snap-on leg straps"],
        unitWeight: "0.8 kg to 1.2 kg",
      },
      imageUrl: [
        "/cowboy-chaps/leather-hay-chap-1.webp",
        "/cowboy-chaps/leather-hay-chap-2.webp",
      ],
      moq: 5,
    },
    {
      id: 5012,
      Sku: "WC-ST-HO-12",
      leatherFinish: "Vegetable-Tanned Heritage Leather",
      metaTitle: "Water Resistant Hermann Oak Western Leather Chaps",
      metaDescription:
        "Premium Hermann Oak Saddle Tan Heritage 1881 leather chaps featuring Oak Guard™ water resistance and drum-milled comfort.",
      slug: "western-leather-chaps-water-resistant-hermann-oak",
      relatedProducts: [5010, 5013],
      productCode: "WC-ST-HO-12",
      title: "Western Leather Chaps, Water Resistant Hermann Oak",
      category: "apparel",
      subCat: "cowboy-chaps",
      description:
        "All-weather vegetable-tanned cowboy chaps with built-in Oak Guard™ water repellency and a soft drum-milled feel.",
      longDescription:
        "Built for men and women who demand durability, comfort and true craftsmanship, these leather fringe cowboy chaps are designed to perform in any conditions, from Montana snow to Texas heat. Made from Hermann Oak’s Saddle Tan Heritage 1881 Top Grain leather, they offer natural water resistance and vegetable-tanned insulation for year-round comfort.",
      specifications: {
        leadTimeDays: 25,
        leatherType: "Hermann Oak Saddle Tan Heritage 1881 Top Grain Leather",
        availableSizes: ["S", "M", "L", "XL"],
        availableColors: ["Saddle Tan with Contrasting Brown Pocket"],
        customizationOptions: [
          "Adjustable stainless steel front and back waist hardware",
          "Tie string ring additions",
        ],
        unitWeight: "1.8 kg to 2.8 kg",
      },
      imageUrl: [
        "/cowboy-chaps/western-leather-chaps-hermann-oak-1.webp",
        "/cowboy-chaps/western-leather-chaps-hermann-oak-2.webp",
      ],
      moq: 1,
    },
    {
      id: 5013,
      Sku: "SC-BR-OIL-13",
      leatherFinish: "Full Grain Oil-Tanned Leather",
      metaTitle: "Western Leather Shotgun Chap | Supple Riding Chaps",
      metaDescription:
        "Classic straight-leg shotgun style leather chaps. Durable brown oil-tanned cowhide with full-length leg zippers.",
      slug: "western-leather-shotgun-chap",
      relatedProducts: [5010, 5012],
      productCode: "SC-BR-OIL-13",
      title: "Western Leather Shotgun Chap",
      category: "apparel",
      subCat: "cowboy-chaps",
      description:
        "Straight-leg style shotgun chaps providing full-length coverage and rugged durability for long riding days.",
      longDescription:
        "Timeless craftsmanship meets everyday performance in these shotgun-style leather chaps. Crafted from quality brown full grain oil-tanned leather, they deliver durable protection from brush, weather and the rigors of ranch work. Features full-length leg zippers, a back buckle closure, and a front tie closure.",
      specifications: {
        leadTimeDays: 15,
        leatherType: "Brown Full Grain Oil-Tanned Leather",
        availableSizes: ["S", "M", "L", "XL"],
        availableColors: ["Brown"],
        customizationOptions: [
          "Adjustable back buckle and front tie closure system",
        ],
        unitWeight: "1.6 kg to 2.6 kg",
      },
      imageUrl: ["/cowboy-chaps/western-leather-shotgun-chap-1.webp"],
      moq: 3,
    },
    {
      id: 5014,
      Sku: "YCh-BR-BW-14",
      leatherFinish: "Supple Cowhide Leather",
      metaTitle: "Youth Leather Cowboy Chinks | Kids Basketweave Chinks",
      metaDescription:
        "Youth-friendly western leather chinks for boys or girls. Features basketweave yokes, berry edge conchos, and adjustable waist.",
      slug: "youth-leather-cowboy-chinks-boys-or-girls-basketweave",
      relatedProducts: [5010, 5013],
      productCode: "YCh-BR-BW-14",
      title: "Youth Leather Cowboy Chinks, Boys or Girls, Basketweave",
      category: "apparel",
      subCat: "cowboy-chaps",
      description:
        "Soft and durable youth cowhide chinks detailed with basketweave trim and stainless steel quick-on snaps.",
      longDescription:
        "Tailored for young riders, these supple cowhide leather chinks offer a perfect mix of protection and western flair. Decorated with classic basketweave yokes, leg trim, and berry edge conchos, they come equipped with double-buckle waist adjustments and secure leg snaps for quick use.",
      specifications: {
        leadTimeDays: 12,
        leatherType: "Supple Brown Cowhide Leather",
        availableSizes: ["Youth Standard (Waist 22”-30.5”)"],
        availableColors: ["Brown with Basketweave Detailing"],
        customizationOptions: [
          "Adjustable waist double-buckles",
          "Stainless steel quick snap leg adjustments",
        ],
        unitWeight: "0.9 kg to 1.4 kg",
      },
      imageUrl: [
        "/cowboy-chaps/youth-leather-cowboy-chinks-basketweave-1.webp",
        "/cowboy-chaps/youth-leather-cowboy-chinks-basketweave-2.webp",
        "/cowboy-chaps/youth-leather-cowboy-chinks-basketweave-3.webp",
      ],
      moq: 2,
    },
];

export default apparel;
