const sports = [
  {
    id: 7001,
    productCode: "GLV-ERG-BLK-01",
    Sku: "GLV-ERG-BLK-01-SU",
    title: "ErgoBlack Performance Golf Glove",
    slug: "ergoblack-performance-golf-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Smooth Matte Cabretta",
    description:
      "Ergonomic white golf glove with black knuckle flexibility insert.",
    longDescription:
      "Designed for maximum range of motion, the ErgoBlack features a specialized black stretch-fabric insert across the knuckles. This design reduces hand fatigue and ensures a tight yet comfortable grip during the swing.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/1ErgoBlack-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "ErgoBlack Performance Golf Glove | Premium Cabretta Leather",
    metaDescription:
      "Shop the ErgoBlack Performance Golf Glove featuring premium Cabretta leather and an ergonomic black knuckle stretch insert for maximum range of motion.",
    relatedProducts: [7003, 7005, 7016],
  },
  {
    id: 7002,
    productCode: "GLV-GRN-DRV-02",
    Sku: "GLV-GRN-DRV-02-SU",
    title: "GreenDrive Tour Glove",
    slug: "greendrive-tour-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Premium Soft Grain",
    description:
      "Classic white glove with vibrant green piping and finger gussets.",
    longDescription:
      "The GreenDrive combines classic styling with modern flair. Featuring green contrast piping on the back of the hand and matching green finger gussets, it offers style alongside performance-grade ventilation.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/2GreenDrive-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "GreenDrive Tour Golf Glove - Premium Cabretta Leather",
    metaDescription:
      "Elevate your game with the GreenDrive Tour Glove. Features classic white Cabretta leather with vibrant green contrast piping and ventilated finger gussets.",
    relatedProducts: [7006, 7011, 7005],
  },
  {
    id: 7003,
    productCode: "GLV-TGR-PLM-03",
    Sku: "GLV-TGR-PLM-03-SU",
    title: "TigerPalm Stability Glove",
    slug: "tigerpalm-stability-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Smooth Matte Cabretta",
    description:
      "White golf glove featuring triple diagonal black stability stripes.",
    longDescription:
      "Built for a secure lock-down feel, the TigerPalm utilizes three diagonal black bands across the back of the hand. These bands provide structural support while maintaining the flexibility needed for a smooth swing.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/3TigerPalm-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "TigerPalm Stability Golf Glove | Structural Support",
    metaDescription:
      "Discover the TigerPalm Stability Golf Glove. Premium Cabretta leather with triple diagonal black bands for ultimate wrist support and structural lock-down.",
    relatedProducts: [7001, 7005, 7013],
  },
  {
    id: 7004,
    productCode: "GLV-BLU-SPR-04",
    Sku: "GLV-BLU-SPR-04-SU",
    title: "BlueSprint Air-Flow Glove",
    slug: "bluesprint-air-flow-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Perforated Soft Finish",
    description: "Breathable white glove with blue mesh knuckle inserts.",
    longDescription:
      "The BlueSprint is engineered for hot weather play. It features distinct blue mesh ovals over the knuckles and blue side panels on the fingers, maximizing airflow and moisture wicking to keep hands dry.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/4BlueSprint-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "BlueSprint Air-Flow Golf Glove - Hot Weather Performance",
    metaDescription:
      "Stay cool under pressure with the BlueSprint Air-Flow Golf Glove. Features blue mesh knuckle vents and premium moisture-wicking Cabretta leather.",
    relatedProducts: [7012, 7015, 7001],
  },
  {
    id: 7005,
    productCode: "GLV-BLK-DRV-05",
    Sku: "GLV-BLK-DRV-05-SU",
    title: "BlackDrive Contour Glove",
    slug: "blackdrive-contour-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Premium Soft Grain",
    description:
      "White glove with dark contrast piping and contoured finger designs.",
    longDescription:
      "A sleek sibling to the GreenDrive, the BlackDrive offers a sharper look with dark contour piping. It provides a consistent fit with flexible finger inserts that conform to the hand's natural shape.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/5BlackDrive-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "BlackDrive Contour Golf Glove | Sleek Classic Design",
    metaDescription:
      "Shop the BlackDrive Contour Golf Glove. Offers premium white Cabretta leather with dark contour piping and flexible finger inserts for an all-weather grip.",
    relatedProducts: [7002, 7001, 7007],
  },
  {
    id: 7006,
    productCode: "GLV-GRN-EDG-06",
    Sku: "GLV-GRN-EDG-06-SU",
    title: "GreenEdge Premium Leather Glove",
    slug: "greenedge-premium-leather-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Textured Grain Finish",
    description: "Full green leather construction with a premium grain finish.",
    longDescription:
      "Stand out on the course with the GreenEdge. Unlike standard white gloves, this features a full forest-green leather construction with a distinct grain texture, offering a unique aesthetic without compromising on professional-grade grip.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/6GreenEdge-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "GreenEdge Premium Forest Green Golf Glove",
    metaDescription:
      "Stand out with the GreenEdge Premium Leather Golf Glove. Full forest-green Cabretta leather construction featuring a unique textured grain grip.",
    relatedProducts: [7002, 7011, 7008],
  },
  {
    id: 7007,
    productCode: "GLV-SHD-MST-07",
    Sku: "GLV-SHD-MST-07-SU",
    title: "ShadowMaster Elite Glove",
    slug: "shadowmaster-elite-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Matte Jet Black",
    description:
      "Sleek all-black golf glove with a stealthy, professional finish.",
    longDescription:
      "The ShadowMaster is designed for the player who prefers a sharp, monochrome aesthetic. Crafted entirely from premium black leather, it offers a sophisticated look that hides dirt while providing a tour-level grip and feel.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/7ShadowMaster-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "ShadowMaster Elite Black Golf Glove | Tour Level Grip",
    metaDescription:
      "Go stealth with the ShadowMaster Elite Glove. Full premium jet black Cabretta leather construction designed for dirt resistance and tour-level tactile response.",
    relatedProducts: [7010, 7015, 7005],
  },
  {
    id: 7008,
    productCode: "GLV-CAM-STL-08",
    Sku: "GLV-CAM-STL-08-SU",
    title: "CamouStealth Tour Glove",
    slug: "camoustealth-tour-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Printed Matte Cabretta",
    description: "Tactical desert camouflage glove for a bold, rugged style.",
    longDescription:
      "Break away from tradition with the CamouStealth. Featuring a unique desert camo pattern printed on high-grade leather, this glove combines tactical style with the soft, responsive feel required for precision shot-making.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/8CamouStealth-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "CamouStealth Tour Golf Glove - Desert Camouflage",
    metaDescription:
      "Unleash bold style with the CamouStealth Tour Glove. Premium printed Cabretta leather in desert camo with a reinforced palm patch for extra durability.",
    relatedProducts: [7009, 7014, 7013],
  },
  {
    id: 7009,
    productCode: "GLV-SAH-PLM-09",
    Sku: "GLV-SAH-PLM-09-SU",
    title: "SaharaPalm Classic Glove",
    slug: "saharapalm-classic-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Natural Suede-Touch",
    description:
      "Natural sand-colored glove offering a clean, earthy aesthetic.",
    longDescription:
      "The SaharaPalm features a distinct beige tone that offers a softer, more natural alternative to stark white gloves. It pairs perfectly with khaki apparel and provides the ultimate soft-touch experience.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/9SaharaPalm-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "SaharaPalm Classic Beige Golf Glove | Earthy Style",
    metaDescription:
      "Shop the SaharaPalm Classic Glove in natural sand beige Cabretta leather. Offers an elegant alternative to white with an ultra soft-touch finish.",
    relatedProducts: [7008, 7011, 7012],
  },
  {
    id: 7010,
    productCode: "GLV-GRY-MST-10",
    Sku: "GLV-GRY-MST-10-SU",
    title: "GrayMaster Pro Glove",
    slug: "graymaster-pro-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Deep Satin Charcoal",
    description: "Deep charcoal gray glove for a modern, sophisticated look.",
    longDescription:
      "The GrayMaster bridges the gap between black and white with a rich charcoal hue. This versatile color hides wear effectively while delivering the premium tackiness and flexibility expected from top-tier equipment.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/10GrayMaster-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "GrayMaster Pro Charcoal Golf Glove - Top Tier Grip",
    metaDescription:
      "Discover the GrayMaster Pro Glove in rich charcoal gray. Hides wear and tear while delivering premium tackiness and deep contrast black piping aesthetics.",
    relatedProducts: [7012, 7007, 7015],
  },
  {
    id: 7011,
    productCode: "GLV-OLV-TCT-11",
    Sku: "GLV-OLV-TCT-11-SU",
    title: "OliveTact Field Glove",
    slug: "olivetact-field-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Tactical Matte Olive",
    description: "Military-inspired olive green glove with a matte finish.",
    longDescription:
      "Embrace a tactical edge with the OliveTact. The muted olive green leather offers a unique, rugged appearance on the course, complemented by superior durability and a consistent, non-slip grip in varying weather conditions.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/11OliveTact-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "OliveTact Field Golf Glove | Tactical Olive Drab",
    metaDescription:
      "Get rugged style with the OliveTact Field Glove. Crafted from durable matte olive green Cabretta leather, engineered for reliable all-season performance.",
    relatedProducts: [7006, 7008, 7009],
  },
  {
    id: 7012,
    productCode: "GLV-GRP-GRY-12",
    Sku: "GLV-GRP-GRY-12-SU",
    title: "GraphiteGray Performance Glove",
    slug: "graphitegray-performance-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Cool-Touch Light Matte",
    description:
      "Light gray glove offering a clean, contemporary alternative to white.",
    longDescription:
      "The GraphiteGray offers a lighter, misty gray tone that looks sharp and modern. It reflects sunlight better than darker gloves to keep hands cool, while the premium leather construction ensures a second-skin fit.",

    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/12GraphiteGray-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "GraphiteGray Performance Golf Glove | Misty Lighter Tones",
    metaDescription:
      "Keep cool with the GraphiteGray Performance Glove. Modern light gray Cabretta leather finish designed to reflect sunlight and provide a second-skin fit.",
    relatedProducts: [7010, 7004, 7014],
  },
  {
    id: 7013,
    productCode: "GLV-WLD-STR-13",
    Sku: "GLV-WLD-STR-13-SU",
    title: "WildStrike Patterned Glove",
    slug: "wildstrike-patterned-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Exotic Textured Pattern",
    description:
      "Bold graphite glove featuring a high-contrast animal print pattern.",
    longDescription:
      "Make a statement with the WildStrike. This glove features an intricate leopard and zebra inspired pattern across the entire back of the hand. Crafted from premium leather, it provides a fierce look without sacrificing the soft touch required for professional play.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/13WildStrike-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "WildStrike Patterned Golf Glove - Exotic Animal Print",
    metaDescription:
      "Stand out with the WildStrike Patterned Golf Glove. Features a distinct graphite animal print layout built on high-grade flexible Cabretta leather.",
    relatedProducts: [7008, 7014, 7003],
  },
  {
    id: 7014,
    productCode: "GLV-SNW-WHT-14",
    Sku: "GLV-SNW-WHT-14-SU",
    title: "SnowWhite Arctic Camo Glove",
    slug: "snowwhite-arctic-camo-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Printed Frost Finish",
    description:
      "White base glove with a stylish light gray and black arctic camo pattern.",
    longDescription:
      "The SnowWhite offers a modern take on camouflage. Using a palette of white, frost gray, and charcoal, this arctic camo design provides a clean yet rugged aesthetic that stands out on the green.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/14SnowWhite-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "SnowWhite Arctic Camo Golf Glove | Frost Pattern",
    metaDescription:
      "Explore the SnowWhite Arctic Camo Golf Glove. Combines clean white, frost gray, and charcoal elements with moisture-control Cabretta leather performance.",
    relatedProducts: [7008, 7015, 7012],
  },
  {
    id: 7015,
    productCode: "GLV-GHS-GRP-15",
    Sku: "GLV-GHS-GRP-15-SU",
    title: "GhostGrip Night Camo Glove",
    slug: "ghostgrip-night-camo-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Printed Matte Cabretta",
    description:
      "Dark-toned glove featuring a navy and charcoal 'night camo' pattern.",
    longDescription:
      "Designed for the player who prefers darker tones, the GhostGrip utilizes a 'night camo' pattern. The blend of navy and slate gray provides a tactical look that is both stylish and functional for all-day play.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/15GhostGrip-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "GhostGrip Night Camo Golf Glove - Navy & Charcoal",
    metaDescription:
      "Shop the GhostGrip Night Camo Golf Glove. Offers an elegant navy and charcoal tactical night camo pattern with a high-tack soft grip surface.",
    relatedProducts: [7007, 7014, 7010],
  },
  {
    id: 7016,
    productCode: "GLV-RED-FLS-16",
    Sku: "GLV-RED-FLS-16-SU",
    title: "RedFlash Velocity Glove",
    slug: "redflash-velocity-glove",
    category: "sports",
    subCat: "golf-gloves",
    leatherFinish: "Smooth Matte Cabretta",
    description:
      "White performance glove with aggressive red 'swoosh' accents.",
    longDescription:
      "The RedFlash is built for speed and style. Featuring a bold red swoosh across the back of the hand and matching red finger gussets, this glove offers high visibility and a sporty, athletic fit.",
    specifications: {
      leadTimeDays: 7,
      customizationOptions: [
        "custom logo",
        "Custom knuckle stretch fabric color",
        "Sizing adjustments (Cadet vs. Regular fit)",
        "Custom velcro strap design",
        "Perforation density configuration",
      ],
      leatherType: "Premium Grade AAA Cabretta Leather (Sheepskin)",
      hardwareMaterial: "Reinforced Micro-Velcro Hook-and-Loop Tab",
      availableSizes: ["S", "M", "ML", "L", "XL", "XXL"],
      gloveWidth: "Standard Adult Ergonomic Fit",
      leatherThickness: "0.45 mm to 0.55 mm (Ultra-thin for maximum club feel)",
      closureType: "Adjustable Ergonomic Slanted Strap",
      cuffWidth: "Elasticated Form-Fitting Wristband",
      numberOfHands: "1 (Single Left or Right Hand Fit)",
      stitchingPitch: "Fine 2.0 mm Double-Row Performance Stitching",
      palmStyle: "Reinforced High-Tack Palm Patch",
      availableColors: [
        "White",
        "Jet Black",
        "Forest Green",
        "Charcoal Gray",
        "Sand Beige",
        "Olive Green",
        "Light Gray",
        "Desert Camo",
        "Arctic Camo",
        "Night Camo",
      ],
      unitWeight: "0.04 kg to 0.06 kg",
    },
    imageUrl: ["/Golf-Gloves/16RedFlash-Golf-Glove.jpg"],
    moq: 10,
    metaTitle: "RedFlash Velocity Golf Glove | Sporty High Visibility",
    metaDescription:
      "Get noticed with the athletic RedFlash Velocity Golf Glove. Premium Cabretta leather construction with high-visibility sporty red accent swooshes.",
    relatedProducts: [7001, 7002, 7005],
  },

  // ---------baseball gloves start---------

  {
    id: "BG-1",
    sku: "BG-ASE-001",
    productCode: "BG-ASE-001",
    title: "AllStar USA Elite Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Smooth Topo-Embossed Finish",
    metaTitle:
      "AllStar USA Elite Baseball Batting Gloves | White Red Navy | Premium Leather",
    metaDescription:
      "The AllStar USA Elite batting gloves bring premium performance and patriotic style together in a White, Red, and Navy colorway. Built with a full-grain topo-embossed leather palm, hexagonal perforated knuckle guard, and hook-and-loop wrist strap for serious adult players.",
    description:
      "A full-grain topo-embossed leather palm and hexagonal perforated knuckle guard deliver elite grip, comfort, and protection for competitive adult players.",
    longDescription:
      "The full-grain cabretta leather palm features a subtle topographic emboss that provides unmatched grip and durability through hundreds of swings. The stretch synthetic back panel carries a signature topo-map print for flexibility without sacrificing structure, while the hexagonal perforated leather knuckle guard adds impact protection with airflow. A hook-and-loop wrist strap with embossed badge ensures a secure, customizable fit, and finger vents keep hands cool throughout the game.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Stretch synthetic with topo-map print",
      knuckleGuard: "Hexagonal perforated leather pad",
      wristClosure: "Hook-and-loop + embossed badge strap",
      ventilation: "Finger vents + knuckle perforations",
      fingerPiping: "White contrast piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Premium",
      color: "White / Red / Navy",
      soldAs: "Pair",
    },
    relatedProducts: [2, 8, 14],
    imageUrl: ["/BaseBall-Batting-Gloves/allstar-elite-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-2",
    sku: "BG-ART-002",
    productCode: "BG-ART-002",
    title: "Arctic Topo Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Off-White Matte Finish",
    metaTitle:
      "Arctic Topo Baseball Batting Gloves | All White Ghost Edition | Premium Leather",
    metaDescription:
      "The Arctic Topo batting gloves deliver a full whiteout monochrome look with a topo-map embossed synthetic back, octagonal perforated knuckle pad, and a premium off-white leather palm. Designed for elite adult players who prefer clean, understated style.",
    description:
      "The Arctic Topo is a full whiteout premium batting glove built for players who let their game do the talking. Ghost-white from palm to wrist, it features a topo-map embossed back panel and an octagonal perforated knuckle pad for a commanding presence at the plate.",
    longDescription:
      "The Arctic Topo Batting Glove is the ultimate all-white performance glove for the style-conscious adult player. The off-white full-grain cabretta leather palm provides elite grip and natural feel, while the topo-map embossed synthetic back adds premium textural depth that catches the light beautifully. The octagonal perforated knuckle pad features a subtle logo patch for ventilation and mild impact protection.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Topo-map embossed synthetic, all white",
      knuckleGuard: "Octagonal perforated pad + logo patch",
      wristClosure: "Hook-and-loop strap + topo wrist badge",
      ventilation: "Knuckle pad perforations + finger vents",
      fingerPiping: "White-on-white piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Premium",
      color: "All White / Ghost, customizable",
      soldAs: "Pair",
    },
    relatedProducts: [1, 8, 12],
    imageUrl: ["/BaseBall-Batting-Gloves/arctic-topo-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-3",
    sku: "BG-BLV-003",
    productCode: "BG-BLV-003",
    title: "Bolt Velocity Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Perforated Synthetic Mesh – Matte White Finish",
    metaTitle:
      "Bolt Velocity Baseball Batting Gloves | Black White | Aggressive Graphic Design",
    metaDescription:
      "The Bolt Velocity batting gloves combine a breathable perforated mesh palm with a bold geometric graphic back panel and black molded finger panels. A high-energy mid-range glove built for adult baseball players who play fast.",
    description:
      "The Bolt Velocity is built for speed and aggression, combining a breathable perforated mesh palm with a bold black-and-white geometric graphic back panel that turns heads on every swing.",
    longDescription:
      "The Bolt Velocity Batting Glove is designed for the high-energy adult player who wants both performance and an eye-catching look. The hard synthetic back panel is printed with a bold geometric slash graphic for a distinctive visual identity, while black molded finger panels add protection without restricting movement. An elastic knit cuff band provides a snug slip-on fit with no traditional strap, and combined mesh palm and back panel perforations make this one of the most ventilated gloves on the field.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Hard synthetic + bold geometric graphic",
      knuckleGuard: "Black molded finger panels",
      wristClosure: "Elastic knit cuff band, no strap",
      ventilation: "Mesh palm + back panel perforations",
      fingerPiping: "Bold black contrast piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Black / White",
      soldAs: "Pair",
    },
    relatedProducts: [9, 11, 13],
    imageUrl: ["/BaseBall-Batting-Gloves/bolt-velocity-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-4",
    sku: "BG-CRC-004",
    productCode: "BG-CRC-004",
    title: "Crimson Core Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Pearl White Smooth Finish",
    metaTitle:
      "Crimson Core Baseball Batting Gloves | Red White | Full-Grain Leather Palm",
    metaDescription:
      "The Crimson Core batting gloves pair a premium pearl white full-grain leather palm with a bold solid red synthetic back and perforated knuckle pad. A standout mid-range glove for adult baseball players who want performance and high-visibility style.",
    description:
      "The Crimson Core is a striking Red and White batting glove that pairs a premium pearl white full-grain leather palm with a vivid solid red synthetic back panel for a bold, high-visibility look at the plate.",
    longDescription:
      "The Crimson Core Batting Glove is built for the adult player who wants premium leather feel paired with a bold, high-visibility colorway. The pearl white full-grain cabretta leather palm delivers excellent grip, natural feel, and long-lasting durability, while the solid red synthetic stretch back offers flexibility and striking visual contrast.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Solid red synthetic stretch",
      knuckleGuard: "Red perforated leather pad + logo patch",
      wristClosure: "Wide hook-and-loop velcro strap",
      ventilation: "Knuckle pad perforations + finger vents",
      fingerPiping: "Red contrast finger piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Red / White",
      soldAs: "Pair",
    },
    relatedProducts: [1, 7, 11],
    imageUrl: ["/BaseBall-Batting-Gloves/crimson-core-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-5",
    sku: "BG-DMD-005",
    productCode: "BG-DMD-005",
    title: "Diamond Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish:
      "Full-Grain Cabretta Leather – White Smooth Finish with Flame Emboss",
    metaTitle:
      "Diamond Baseball Batting Gloves | White Black | Geometric Leather Design",
    metaDescription:
      "The Diamond batting gloves feature a full-grain white leather palm with flame emboss, bold black angular back panels, and heavy contrast stitching throughout. A mid-range glove with sharp geometric style built for adult players.",
    description:
      "The Diamond batting glove merges a clean white full-grain leather palm with bold black angular back panels and a flame-embossed logo for a sharp geometric design built for the adult player who demands structured style.",
    longDescription:
      "The Diamond Batting Glove is a mid-range option for adult players who want a structured, visually bold glove without compromising on palm quality. The white full-grain cabretta leather palm features a flame-embossed logo at the heel for premium grip and a distinctive identity. The back construction uses white leather panels intersected by sharp black angular sections for a geometric aesthetic that stands out on the field.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "White leather + black angular panels",
      knuckleGuard: "Black segmented side panels",
      wristClosure: "Wide elastic wrist band",
      ventilation: "Finger vents on back panel",
      fingerPiping: "Black contrast stitching throughout",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "White / Black",
      soldAs: "Pair",
    },
    relatedProducts: [6, 12, 13],
    imageUrl: ["/BaseBall-Batting-Gloves/diamond-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-6",
    sku: "BG-HTX-006",
    productCode: "BG-HTX-006",
    title: "Heritage Tuxedo Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Matte Black Classic Finish",
    metaTitle:
      "Heritage Tuxedo Baseball Batting Gloves | Black White | Classic Leather Build",
    metaDescription:
      "The Heritage Tuxedo batting gloves offer a timeless black-and-white leather build with white V-stitch back accents, a grey thumb panel, and a clean elastic knit cuff. A classic mid-range leather glove for adult players who value tradition.",
    description:
      "The Heritage Tuxedo is a classic black-and-white leather batting glove built for the traditionalist adult player. White V-stitch back accents and a refined grey thumb panel complete its clean, professional aesthetic.",
    longDescription:
      "The Heritage Tuxedo Batting Glove pays homage to classic leather glove design while delivering modern-day performance. The full-grain cabretta leather palm in matte black provides superior grip and durability, breaking in beautifully with use. The back panel mirrors the same premium leather construction, accented with crisp white V-stitching that references traditional baseball craftsmanship. The wide elastic knit cuff delivers a clean, minimal silhouette and fast slip-on experience, making this the ideal glove for adult players who value tradition over flashy graphics.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Black leather + white V-stitch accents",
      knuckleGuard: "Grey thumb panel accent",
      wristClosure: "Wide elastic knit cuff, no strap",
      ventilation: "Minimal — solid leather construction",
      fingerPiping: "White contrast piping on fingers",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Black / White",
      soldAs: "Pair",
    },
    relatedProducts: [5, 9, 12],
    imageUrl: ["/BaseBall-Batting-Gloves/heritage-tuxedo-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-7",
    sku: "BG-IVP-007",
    productCode: "BG-IVP-007",
    title: "Ivory Viper Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Textured Pebbled Leather – Ivory Matte Finish",
    metaTitle:
      "Ivory Viper Baseball Batting Gloves | Cream Black | Reptile Print Back Panel",
    metaDescription:
      "The Ivory Viper batting gloves pair a textured ivory pebbled leather palm with a bold black viper scale synthetic back for a high-contrast, aggressive look on the field. A unique mid-range glove for adult players who want to stand out.",
    description:
      "The Ivory Viper features a textured ivory pebbled leather palm paired with a bold black reptile-print synthetic back for a high-contrast, aggressive look that sets it apart from anything else on the field.",
    longDescription:
      "The Ivory Viper Batting Glove brings a truly distinctive look to the mid-range category. The palm is crafted from textured pebbled leather in a warm ivory finish, providing natural grip through surface texture rather than synthetic coatings for lasting durability and feel. The back panel uses a black synthetic material printed with a striking snake scale pattern, creating an aggressive aesthetic with strong visual contrast. A hexagonal embossed velcro strap delivers a secure, modern wrist closure built for adult players who want to stand out without sacrificing quality.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Black snake/viper-print synthetic",
      knuckleGuard: "None — integrated back panel",
      wristClosure: "Hexagonal embossed velcro strap",
      ventilation: "Minimal — palm pebble texture only",
      fingerPiping: "Ivory contrast on black back",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Cream / Black",
      soldAs: "Pair",
    },
    relatedProducts: [3, 4, 11],
    imageUrl: ["/BaseBall-Batting-Gloves/ivory-viper-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-8",
    sku: "BG-ONT-008",
    productCode: "BG-ONT-008",
    title: "Onyx Topo Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Matte Black Luxury Finish",
    metaTitle:
      "Onyx Topo Baseball Batting Gloves | Black Gold | Luxury Topo-Map Design",
    metaDescription:
      "The Onyx Topo batting gloves feature a matte black full-grain leather palm, black-on-black topo-map embossed back, gold metallic finger accents, and a perforated leather knuckle pad. A premium luxury batting glove for adult players who demand the best.",
    description:
      "The Onyx Topo is a black-on-black premium batting glove with gold metallic finger accents, a topo-map embossed back panel, and a perforated leather knuckle pad with a gold-stripe badge for dark luxury at the highest level.",
    longDescription:
      "The Onyx Topo Batting Glove represents the pinnacle of dark luxury in performance glove design. The matte black full-grain cabretta leather palm delivers elite grip and bat control, while the back panel carries a subtle black-on-black topo-map emboss that adds depth and texture without disrupting the stealthy colorway. Gold metallic accents at the fingertips and on the knuckle pad badge introduce a premium detail that elevates the glove to collector quality.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Topo-map embossed synthetic, black",
      knuckleGuard: "Perforated leather pad + gold-stripe badge",
      wristClosure: "Hook-and-loop + topo-embossed wrist badge",
      ventilation: "Knuckle pad perforations + finger tip vents",
      fingerPiping: "Gold metallic finger tip accents",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Premium",
      color: "Black / Gold",
      soldAs: "Pair",
    },
    relatedProducts: [1, 2, 14],
    imageUrl: ["/BaseBall-Batting-Gloves/onyx-topo-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-9",
    sku: "BG-RPE-009",
    productCode: "BG-RPE-009",
    title: "Raptor Elite Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Matte Black Stealth Finish",
    metaTitle:
      "Raptor Elite Baseball Batting Gloves | All Black Blackout | Slash Graphic Design",
    metaDescription:
      "The Raptor Elite batting gloves are a fully stealth all-black mid-range glove featuring a matte full-grain leather palm, bold slash graphic back panel, and integrated molded knuckle panels. Built for adult players who prefer to let their performance speak.",
    description:
      "The Raptor Elite is a fully stealth all-black batting glove with a signature slash graphic back panel and matte full-grain leather palm, built for the adult player who prefers to make an impact without making a statement.",
    longDescription:
      "The Raptor Elite Batting Glove is engineered for the adult player who prefers an intimidating all-black setup with aggressive design detailing. The matte black full-grain cabretta leather palm delivers reliable grip and a refined feel against the bat handle. The black synthetic back panel carries a bold slash graphic pattern rendered in tonal black-on-black that catches light at different angles.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Black synthetic + slash/feather graphic",
      knuckleGuard: "Integrated molded back panels",
      wristClosure: "Hook-and-loop velcro strap",
      ventilation: "Back panel cutouts + palm perforations",
      fingerPiping: "Black-on-black tone piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "All Black / Blackout",
      soldAs: "Pair",
    },
    relatedProducts: [3, 6, 10],
    imageUrl: ["/BaseBall-Batting-Gloves/raptor-elite-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-10",
    sku: "BG-SMH-010",
    productCode: "BG-SMH-010",
    title: "Shadow Mesh Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Genuine Leather Palm Section – White Smooth Finish",
    metaTitle:
      "Shadow Mesh Baseball Batting Gloves | Black White | High-Airflow Mesh Back",
    metaDescription:
      "The Shadow Mesh batting gloves feature a white leather palm, a maximum-airflow black waffle mesh back, a perforated leather knuckle badge, and a chevron-trimmed elastic knit wrist band. The top choice for adult players who prioritize breathability.",
    description:
      "The Shadow Mesh pairs a white leather palm with a full black waffle mesh back panel for maximum airflow and a chevron-trimmed knit wrist band for a clean, modern fit built for warm-weather play.",
    longDescription:
      "The Shadow Mesh Batting Glove is the top choice for adult players who prioritize breathability and comfort during long games and warm-weather play. The white leather palm delivers reliable grip and natural feel, while the back of the hand is covered in a black waffle bubble mesh textile that offers dramatically greater airflow than traditional synthetic or leather backs. The knitted elastic cuff with chevron wrist trim and dual-panel strap ensures a snug, modern fit, and white contrast stripes along the back break up the dark mesh for a clean, contrasted finish.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Waffle/bubble mesh textile, black",
      knuckleGuard: "Perforated leather knuckle badge",
      wristClosure: "Knitted elastic cuff + chevron wrist trim",
      ventilation: "Full mesh back — maximum breathability",
      fingerPiping: "White contrast stripes on back",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Black / White",
      soldAs: "Single (one glove shown)",
    },
    relatedProducts: [3, 9, 11],
    imageUrl: ["/BaseBall-Batting-Gloves/shadow-mesh-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-11",
    sku: "BG-STW-011",
    productCode: "BG-STW-011",
    title: "Stealth Wave Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – White with Flame Logo Emboss",
    metaTitle:
      "Stealth Wave Baseball Batting Gloves | Black White | Wave-Cut Two-Tone Design",
    metaDescription:
      "The Stealth Wave batting gloves feature a full-grain white leather palm with flame logo emboss, bold wave-cut black nylon back panels, and perforated mesh ventilation sections. A mid-range glove for adult players who want speed and visual impact.",
    description:
      "The Stealth Wave features a white full-grain leather palm with flame logo and a bold wave-cut black nylon back panel for a fast, fluid two-tone aesthetic built for the adult player who wants performance and strong visual impact.",
    longDescription:
      "The Stealth Wave Batting Glove is built for the adult player who wants a glove that feels as fast as their swing. The white full-grain cabretta leather palm features a flame logo emboss at the heel for premium grip and a distinctive identity. The black nylon back panel is intersected by wave-cut white panels that create an energetic, flowing visual pattern, with perforated mesh sections throughout to maintain airflow during active play.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Black nylon + white wave-cut panels",
      knuckleGuard: "None — back panel design only",
      wristClosure: "Hook-and-loop velcro strap",
      ventilation: "Perforated mesh sections on back",
      fingerPiping: "Black/white contrast piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Mid-Range",
      color: "Black / White",
      soldAs: "Pair",
    },
    relatedProducts: [3, 7, 10],
    imageUrl: ["/BaseBall-Batting-Gloves/stealth-wave-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-12",
    sku: "BG-SZP-012",
    productCode: "BG-SZP-012",
    title: "StrikeZone Pro Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish:
      "Full-Grain Cabretta Leather – Monochrome Stealth Grey Smooth Finish",
    metaTitle:
      "StrikeZone Pro Baseball Batting Gloves | Grey | Full All-Leather Premium Build",
    metaDescription:
      "The StrikeZone Pro batting gloves are built entirely from full-grain cabretta leather in a monochrome stealth grey colorway, with V-stitch back paneling, tonal stitching, and a low-profile velcro strap. A premium glove for adult players who let quality speak for itself.",
    description:
      "The StrikeZone Pro is an all-leather monochrome grey batting glove with V-stitch back paneling and tonal grey stitching throughout, built for the serious adult player who lets quality speak for itself.",
    longDescription:
      "The StrikeZone Pro Batting Glove is built entirely from full-grain cabretta leather in a single stealth grey colorway, delivering elite performance without the distraction of graphics or bold colors. The back panel features smooth leather construction with subtle V-stitch paneling that adds structural depth and a classic craftsmanship aesthetic. Grey-on-grey tonal stitching runs throughout the glove, visible only up close, for a refined and understated design detail.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Smooth leather with V-stitch paneling",
      knuckleGuard: "None — full leather back",
      wristClosure: "Low-profile velcro strap, no logo",
      ventilation: "Minimal — solid leather build",
      fingerPiping: "Grey-on-grey tonal stitching",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Premium",
      color: "Monochrome Stealth Grey",
      soldAs: "Pair",
    },
    relatedProducts: [2, 6, 8],
    imageUrl: ["/BaseBall-Batting-Gloves/strikezone-pro-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-13",
    sku: "BG-TTN-013",
    productCode: "BG-TTN-013",
    title: "Titan Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Full-Grain Cabretta Leather – Matte Black Classic Finish",
    metaTitle:
      "Titan Baseball Batting Gloves | Black White | Entry-Level Leather Batting Glove",
    metaDescription:
      "The Titan batting gloves offer a full-grain black leather palm, a white leather and mesh back, a perforated knuckle pad, and a wide elastic knit cuff for a reliable and durable entry-level option for adult baseball players.",
    description:
      "The Titan is a dependable black-and-white entry-level batting glove with a full-grain leather palm, white leather and mesh back, and a perforated knuckle pad built for adult players who need reliable performance at an accessible price point.",
    longDescription:
      "The Titan Batting Glove is designed for the adult player who needs reliable performance at an accessible price point. The full-grain cabretta leather palm in matte black delivers genuine leather feel and grip without the premium price tag. White leather panels on the back are intersected by black mesh textile strips, creating a dual-texture construction that offers both structure and ventilation.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "White leather + black mesh textile strips",
      knuckleGuard: "White leather perforated knuckle pad",
      wristClosure: "Wide elastic knit cuff band",
      ventilation: "Mesh stripe panels + knuckle perforations",
      fingerPiping: "Black/white contrast stitching",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Entry",
      color: "Black / White",
      soldAs: "Pair",
    },
    relatedProducts: [3, 6, 11],
    imageUrl: ["/BaseBall-Batting-Gloves/titan-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-14",
    sku: "BG-WRH-014",
    productCode: "BG-WRH-014",
    title: "Workhorse Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish:
      "Full-Grain Cabretta Leather – Off-White Pearl Smooth Finish",
    metaTitle:
      "Workhorse Baseball Batting Gloves | Navy White | Topo-Map Premium Leather Glove",
    metaDescription:
      "The Workhorse batting gloves feature a pearl white full-grain leather palm, a navy topo-map synthetic back, a perforated knuckle pad, and a topo-embossed wrist badge. A clean and durable premium glove for adult baseball players who train hard.",
    description:
      "The Workhorse combines a pearl white full-grain leather palm with a deep navy topo-map synthetic back for a clean, professional look and a pro-grade feel built to perform season after season.",
    longDescription:
      "The Workhorse Batting Glove earns its name through relentless durability and refined performance. The off-white pearl full-grain cabretta leather palm is soft yet tough enough to withstand a full season of heavy use, providing excellent bat grip and control on every swing. The navy blue synthetic back features a topo-map embossed print that adds premium visual texture and depth.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Navy synthetic + topo-map print",
      knuckleGuard: "Navy perforated leather pad",
      wristClosure: "Hook-and-loop + navy topo wrist badge",
      ventilation: "Knuckle perforations + finger vents",
      fingerPiping: "Navy contrast piping",
      sizing: "Adult S / M / L / XL / XXL",
      targetUser: "Adult",
      tier: "Premium",
      color: "Navy / White",
      soldAs: "Pair",
    },
    relatedProducts: [1, 2, 8],
    imageUrl: ["/BaseBall-Batting-Gloves/workhorse-baseball-glove.png"],
    moq: 10,
  },

  {
    id: "BG-15",
    sku: "BG-YTH-015",
    productCode: "BG-YTH-015",
    title: "Youth Baseball Batting Gloves",
    category: "sports",
    subCat: "baseball-batting-gloves",
    leatherFinish: "Pebbled Embossed Leather – Matte Black Textured Finish",
    metaTitle:
      "Youth Baseball Batting Gloves | Black Charcoal Gold | Kids Batting Glove",
    metaDescription:
      "The Youth batting gloves feature a pebbled leather palm, a charcoal hexagonal quilted back, a gold chevron logo, and laser-perforated ventilation throughout. Sized for young players with an easy hook-and-loop wrist closure.",
    description:
      "The Youth Batting Glove is designed for developing players ready to take their game seriously, featuring a pebbled leather palm, charcoal hex-quilt back panel, and a gold chevron logo for a pro-inspired look in youth sizing.",
    longDescription:
      "The Youth Batting Glove is built specifically for developing players who want to look and feel like the pros. The matte black pebbled embossed leather palm provides excellent grip and bat control suited to youth swing speeds and bat weights. The charcoal hexagonal quilted synthetic back gives the glove a structured, premium appearance while maintaining flexibility for young hands.",
    specifications: {
      palmMaterial: "Perforated Synthetic or Cabretta Leather",
      backMaterial: "Hexagonal quilted synthetic, charcoal",
      knuckleGuard: "Integrated perforated back panels",
      wristClosure: "Low-profile hook-and-loop velcro strap",
      ventilation: "Laser-perforated palm + back panels",
      fingerPiping: "Grey contrast finger piping",
      sizing: "Youth XS / S / M / L",
      targetUser: "Youth",
      tier: "Youth",
      color: "Black / Charcoal / Gold",
      soldAs: "Pair",
    },
    relatedProducts: [3, 13],
    imageUrl: ["/BaseBall-Batting-Gloves/youth-baseball-glove.png"],
    moq: 10,
  },
];

export default sports;
