const sports = [
  {
    id: 7001,
    productCode: "GLV-ERG-BLK-01",
    title: "ErgoBlack Performance Golf Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Ergonomic white golf glove with black knuckle flexibility insert.",
    longDescription:
      "Designed for maximum range of motion, the ErgoBlack features a specialized black stretch-fabric insert across the knuckles. This design reduces hand fatigue and ensures a tight yet comfortable grip during the swing.",
    feature: [
      "Premium Cabretta Leather",
      "Ergonomic Black Knuckle Insert",
      "Perforated Fingers for Breathability",
      "Reinforced Velcro Closure",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Black Insert",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/1ErgoBlack-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7002,
    productCode: "GLV-GRN-DRV-02",
    title: "GreenDrive Tour Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Classic white glove with vibrant green piping and finger gussets.",
    longDescription:
      "The GreenDrive combines classic styling with modern flair. Featuring green contrast piping on the back of the hand and matching green finger gussets, it offers style alongside performance-grade ventilation.",
    feature: [
      "Premium Cabretta Leather",
      "Contrast Green Piping",
      "Ventilated Finger Gussets",
      "Secure Adjustable Strap",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Green Accents",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/2GreenDrive-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7003,
    productCode: "GLV-TGR-PLM-03",
    title: "TigerPalm Stability Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "White golf glove featuring triple diagonal black stability stripes.",
    longDescription:
      "Built for a secure lock-down feel, the TigerPalm utilizes three diagonal black bands across the back of the hand. These bands provide structural support while maintaining the flexibility needed for a smooth swing.",
    feature: [
      "Premium Cabretta Leather",
      "Diagonal Stability Strips",
      "Full Perforation Ventilation",
      "Comfort Elastic Wrist",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Black Stripes",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/3TigerPalm-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7004,
    productCode: "GLV-BLU-SPR-04",
    title: "BlueSprint Air-Flow Glove",
    category: "sports",
    subCat: "golf-gloves",
    description: "Breathable white glove with blue mesh knuckle inserts.",
    longDescription:
      "The BlueSprint is engineered for hot weather play. It features distinct blue mesh ovals over the knuckles and blue side panels on the fingers, maximizing airflow and moisture wicking to keep hands dry.",
    feature: [
      "Premium Cabretta Leather",
      "Blue Mesh Knuckle Vents",
      "Breathable Side Panels",
      "Moisture-Wicking Material",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Blue Mesh",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/4BlueSprint-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7005,
    productCode: "GLV-BLK-DRV-05",
    title: "BlackDrive Contour Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "White glove with dark contrast piping and contoured finger designs.",
    longDescription:
      "A sleek sibling to the GreenDrive, the BlackDrive offers a sharper look with dark contour piping. It provides a consistent fit with flexible finger inserts that conform to the hand's natural shape.",
    feature: [
      "Premium Cabretta Leather",
      "Dark Contour Piping",
      "Flexible Finger Inserts",
      "All-Weather Grip",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Black Accents",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/5BlackDrive-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7006,
    productCode: "GLV-GRN-EDG-06",
    title: "GreenEdge Premium Leather Glove",
    category: "sports",
    subCat: "golf-gloves",
    description: "Full green leather construction with a premium grain finish.",
    longDescription:
      "Stand out on the course with the GreenEdge. Unlike standard white gloves, this features a full forest-green leather construction with a distinct grain texture, offering a unique aesthetic without compromising on professional-grade grip.",
    feature: [
      "Premium Cabretta Leather",
      "Textured Grain Grip",
      "Black Wrist Binding",
      "Classic Perforation Pattern",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Forest Green",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/6GreenEdge-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7007,
    productCode: "GLV-SHD-MST-07",
    title: "ShadowMaster Elite Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Sleek all-black golf glove with a stealthy, professional finish.",
    longDescription:
      "The ShadowMaster is designed for the player who prefers a sharp, monochrome aesthetic. Crafted entirely from premium black leather, it offers a sophisticated look that hides dirt while providing a tour-level grip and feel.",
    feature: [
      "Premium Cabretta Leather",
      "All-Black Stealth Design",
      "Moisture-Wicking Wristband",
      "Precision Fit Technology",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Jet Black",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/7ShadowMaster-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7008,
    productCode: "GLV-CAM-STL-08",
    title: "CamouStealth Tour Glove",
    category: "sports",
    subCat: "golf-gloves",
    description: "Tactical desert camouflage glove for a bold, rugged style.",
    longDescription:
      "Break away from tradition with the CamouStealth. Featuring a unique desert camo pattern printed on high-grade leather, this glove combines tactical style with the soft, responsive feel required for precision shot-making.",
    feature: [
      "Premium Cabretta Leather",
      "Desert Camouflage Pattern",
      "Reinforced Palm Patch",
      "Breathable Perforations",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Desert Camo (Tan/Brown)",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/8CamouStealth-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7009,
    productCode: "GLV-SAH-PLM-09",
    title: "SaharaPalm Classic Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Natural sand-colored glove offering a clean, earthy aesthetic.",
    longDescription:
      "The SaharaPalm features a distinct beige tone that offers a softer, more natural alternative to stark white gloves. It pairs perfectly with khaki apparel and provides the ultimate soft-touch experience.",
    feature: [
      "Premium Cabretta Leather",
      "Natural Sand Colorway",
      "Soft-Touch Finish",
      "Ergonomic Seam Placement",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Sand Beige",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/9SaharaPalm-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7010,
    productCode: "GLV-GRY-MST-10",
    title: "GrayMaster Pro Glove",
    category: "sports",
    subCat: "golf-gloves",
    description: "Deep charcoal gray glove for a modern, sophisticated look.",
    longDescription:
      "The GrayMaster bridges the gap between black and white with a rich charcoal hue. This versatile color hides wear effectively while delivering the premium tackiness and flexibility expected from top-tier equipment.",
    feature: [
      "Premium Cabretta Leather",
      "Deep Charcoal Finish",
      "Contrast Black Piping",
      "Ventilated Finger Stalls",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Charcoal Gray",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/10GrayMaster-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7011,
    productCode: "GLV-OLV-TCT-11",
    title: "OliveTact Field Glove",
    category: "sports",
    subCat: "golf-gloves",
    description: "Military-inspired olive green glove with a matte finish.",
    longDescription:
      "Embrace a tactical edge with the OliveTact. The muted olive green leather offers a unique, rugged appearance on the course, complemented by superior durability and a consistent, non-slip grip in varying weather conditions.",
    feature: [
      "Premium Cabretta Leather",
      "Olive Drab Colorway",
      "Matte Finish",
      "All-Season Durability",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Olive Green",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/11OliveTact-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7012,
    productCode: "GLV-GRP-GRY-12",
    title: "GraphiteGray Performance Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Light gray glove offering a clean, contemporary alternative to white.",
    longDescription:
      "The GraphiteGray offers a lighter, misty gray tone that looks sharp and modern. It reflects sunlight better than darker gloves to keep hands cool, while the premium leather construction ensures a second-skin fit.",
    feature: [
      "Premium Cabretta Leather",
      "Light Graphite Tone",
      "Cool-Touch Performance",
      "Strategic Finger Perforations",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Light Gray",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/12GraphiteGray-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7013,
    productCode: "GLV-WLD-STR-13",
    title: "WildStrike Patterned Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Bold graphite glove featuring a high-contrast animal print pattern.",
    longDescription:
      "Make a statement with the WildStrike. This glove features an intricate leopard and zebra inspired pattern across the entire back of the hand. Crafted from premium leather, it provides a fierce look without sacrificing the soft touch required for professional play.",
    feature: [
      "Premium Cabretta Leather",
      "Full Animal Print Pattern",
      "Contoured Elastic Wrist",
      "Precision Breathability Holes",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Graphite with Animal Print",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/13WildStrike-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7014,
    productCode: "GLV-SNW-WHT-14",
    title: "SnowWhite Arctic Camo Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "White base glove with a stylish light gray and black arctic camo pattern.",
    longDescription:
      "The SnowWhite offers a modern take on camouflage. Using a palette of white, frost gray, and charcoal, this arctic camo design provides a clean yet rugged aesthetic that stands out on the green.",
    feature: [
      "Premium Cabretta Leather",
      "Arctic Camouflage Design",
      "Reinforced Stitching",
      "Moisture-Control Leather",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Arctic Camo (White/Gray/Black)",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/14SnowWhite-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7015,
    productCode: "GLV-GHS-GRP-15",
    title: "GhostGrip Night Camo Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "Dark-toned glove featuring a navy and charcoal 'night camo' pattern.",
    longDescription:
      "Designed for the player who prefers darker tones, the GhostGrip utilizes a 'night camo' pattern. The blend of navy and slate gray provides a tactical look that is both stylish and functional for all-day play.",
    feature: [
      "Premium Cabretta Leather",
      "Night Camouflage Pattern",
      "High-Tack Grip Surface",
      "Flexible Knuckle Zones",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "Night Camo (Navy/Charcoal)",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/15GhostGrip-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7016,
    productCode: "GLV-RED-FLS-16",
    title: "RedFlash Velocity Glove",
    category: "sports",
    subCat: "golf-gloves",
    description:
      "White performance glove with aggressive red 'swoosh' accents.",
    longDescription:
      "The RedFlash is built for speed and style. Featuring a bold red swoosh across the back of the hand and matching red finger gussets, this glove offers high visibility and a sporty, athletic fit.",
    feature: [
      "Premium Cabretta Leather",
      "Bold Red Velocity Accents",
      "Breathable Red Gussets",
      "Adjustable Hook-and-Loop Tab",
    ],
    specifications: {
      material: "Premium Cabretta Leather",
      color: "White with Red Accents",
      type: "Golf Glove",
      dimensions: "Standard Adult Fit",
      compartments: "Single hand fit",
    },
    imageUrl: ["/Golf-Gloves/16RedFlash-Golf-Glove.jpg"],
    moq: 10,
  },
  {
    id: 7017,
    productCode: "BBG-PRO-CM-BRN",
    title: "PRO-SERIES CATCHER'S MITT",
    category: "sports",
    subCat: "baseBall-gloves",
    description:
      "Heavy-duty chocolate leather mitt designed for maximum impact absorption.",
    longDescription:
      "Engineered for the demands of the home plate, this catcher's mitt features extra-thick palm padding and a closed-web design.",
    feature: [
      "Reinforced Thumb Protection",
      "Deep Pocket for Secure Catching",
      "Double-Laced Webbing",
      "Adjustable Wrist Strap",
    ],
    specifications: {
      material: "Full-Grain Steerhide",
      color: "Dark Brown",
      type: "Catcher's Mitt",
      dimensions: "33.5 inch",
      compartments: "Single deep pocket, reinforced finger stalls",
    },
    imageUrl: ["/Base-Balls/Catcher.png"],
    moq: 5,
  },
  {
    id: 7018,
    productCode: "BBG-A2K-OF-BRN",
    title: "A2K OUTFIELD TRAP-WEB GLOVE",
    category: "sports",
    subCat: "baseBall-gloves",
    description:
      "Long-reach outfield glove featuring a classic H-web construction.",
    longDescription:
      "Built for the grass, this outfield glove provides the extended reach necessary for diving catches.",
    feature: [
      "Extended Length for Outfield Reach",
      "Classic H-Web Design",
      "Pro-Level Palm Liner",
      "Dual Welting for Pocket Durability",
    ],
    specifications: {
      material: "Pro Stock Select Leather",
      color: "Saddle Brown",
      type: "Outfield Glove",
      dimensions: "12.75 inch",
      compartments: "5-finger design, deep outfield pocket",
    },
    imageUrl: ["/Base-Balls/Outfield.png"],
    moq: 5,
  },
  {
    id: 7019,
    productCode: "BBG-A2K-IF-BRN",
    title: "A2K INFIELD I-WEB GLOVE",
    category: "sports",
    subCat: "baseBall-gloves",
    description:
      "A shallow-pocket infield glove designed for lightning-fast transfers.",
    longDescription:
      "The infielder's choice. This glove features an I-web pattern preferred by middle infielders for its ability to shed dirt and allow for a quick grip.",
    feature: [
      "I-Web Pattern for Quick Release",
      "Shallow Pocket Design",
      "Moisture-Wicking Wrist Liner",
      "Reinforced Finger Topping",
    ],
    specifications: {
      material: "Premium Kip Leather",
      color: "Cognac Brown",
      type: "Infield Glove",
      dimensions: "11.5 inch",
      compartments: "5-finger design, shallow pocket",
    },
    imageUrl: ["/Base-Balls/Infield.png"],
    moq: 5,
  },
  {
    id: 7020,
    productCode: "BBG-PRO-PT-BRN",
    title: "PRO-ELITE PITCHER'S GLOVE",
    category: "sports",
    subCat: "baseBall-gloves",
    description:
      "Fully closed-web glove designed to conceal grip and pitch selection.",
    longDescription:
      "Designed specifically for the mound, this glove features a unique stitched-pattern closed web to hide pitch selection.",
    feature: [
      "Closed-Stitched Shield Web",
      "Concealing Grip Technology",
      "Lightweight Leather Construction",
      "Padded Palm",
    ],
    specifications: {
      material: "Japanese Tanned Steerhide",
      color: "Walnut Brown",
      type: "Pitcher's Glove",
      dimensions: "12 inch",
      compartments: "5-finger design, fully obscured web",
    },
    imageUrl: ["/Base-Balls/Pitcher.png"],
    moq: 5,
  },
  {
    id: 7021,
    productCode: "BBG-A2K-1B-BRN",
    title: "A2K FIRST BASE MITT",
    category: "sports",
    subCat: "baseBall-gloves",
    description: "Ergonomic first base mitt with a wide scooping area.",
    longDescription:
      "The anchor of the infield. This first base mitt features a curved shape designed to act as a scoop for low throws.",
    feature: [
      "Contoured Scooping Edge",
      "Double-Bar Reinforced Web",
      "Dri-Lex Wrist Lining",
      "Oversized Pocket Construction",
    ],
    specifications: {
      material: "Pro Stock Leather",
      color: "Dark Russet Brown",
      type: "First Base Mitt",
      dimensions: "12.25 inch",
      compartments: "Single oversized scoop pocket",
    },
    imageUrl: ["/Base-Balls/Base.png"],
    moq: 5,
  },
];

export default sports;
