let PET_ACCESSORIES = [
  {
    id: 9100,
    sku: "FP-PC-ATG-BLK-01",
    leatherFinish: "Smooth Premium Finish",
    metaTitle: "Black Leather AirTag Pet Collar | Premium GPS Tracking Collar",
    metaDescription:
      "Premium black leather pet collar with integrated AirTag holder, solid brass hardware, reinforced stitching, and comfortable fit for dogs and pets.",
    slug: "black-leather-airtag-pet-collar",
    relatedProducts: [
      "FP-PC-ATG-BRN-02",
      "FP-PC-ATG-TAN-03",
      "FP-PL-LSH-BLK-04",
    ],
    productCode: "FP-PC-ATG-BLK-01",
    title: "BLACK LEATHER AIRTAG PET COLLAR",
    category: "pet-accessories",
    subCat: "pet-collars",
    imageUrl: "/Pet-Accessories/pet_airtag_leather_collar_black.png",
    description:
      "Premium black leather pet collar featuring a secure integrated AirTag holder and durable brass hardware.",
    longDescription:
      "Crafted from premium full-grain leather, this black pet collar combines luxury, durability, and smart tracking. The integrated AirTag holder keeps your Apple AirTag securely in place, helping you track your pet's location at all times. Featuring solid brass hardware, reinforced stitching, and a comfortable fit, this collar is designed for everyday use while maintaining a sophisticated appearance.",
    specifications: {
      customizationOptions: [
        "Embossed Pet Name",
        "Custom Logo Embossing",
        "Custom Leather Colors",
        "Personalized Name Plate",
        "Custom Hardware Finish",
      ],
      leatherType: "Full-Grain and Top-Grain Cowhide Leather",
      collarWidth: "2 cm to 4 cm",
      collarLength: "25 cm to 70 cm",
      airtagCompatibility: "Apple AirTag Compatible",
      closureType: "Adjustable Buckle Closure",
      hardwareMaterial: "Solid Brass / Antique Brass",
      stitchingType: "Reinforced Edge Stitching",
      edgeFinish: "Hand-Painted / Burnished Edges",
      liningMaterial: "Soft Leather Lining",
      availableColors: [
        "Black",
        "Brown",
        "Tan",
        "Cognac",
        "Navy",
        "Green",
        "Custom Colors Available",
      ],
      suitableFor: ["Dogs", "Cats", "Pets"],
      unitWeight: "0.12 kg to 0.35 kg",
    },
  },
  {
    id: 9101,
    sku: "FP-PC-ATG-BRN-02",
    leatherFinish: "Vintage Pull-Up Finish",
    metaTitle: "Brown Leather AirTag Pet Collar | Premium Tracking Dog Collar",
    metaDescription:
      "Handcrafted brown leather pet collar with integrated AirTag holder, solid brass hardware, contrast stitching, and premium full-grain leather construction.",
    slug: "brown-leather-airtag-pet-collar",
    relatedProducts: [
      "FP-PC-ATG-BLK-01",
      "FP-PC-ATG-TAN-03",
      "FP-PL-LSH-BRN-05",
    ],
    productCode: "FP-PC-ATG-BRN-02",
    title: "BROWN LEATHER AIRTAG PET COLLAR",
    category: "pet-accessories",
    subCat: "pet-collars",
    imageUrl: "/Pet-Accessories/pet_airtag_leather_collar_brown.png",
    description:
      "Premium brown leather pet collar featuring an integrated AirTag holder, contrast stitching, and durable brass hardware.",
    longDescription:
      "Designed for pet owners who value both style and functionality, this handcrafted brown leather AirTag pet collar is made from premium full-grain leather with elegant contrast stitching. The built-in AirTag holder keeps your tracker securely in place, allowing you to monitor your pet's location with confidence. Finished with solid brass hardware and reinforced construction, this collar offers exceptional durability, comfort, and timeless craftsmanship for everyday wear.",
    specifications: {
      customizationOptions: [
        "Embossed Pet Name",
        "Custom Logo Embossing",
        "Personalized Name Tag",
        "Custom Leather Colors",
        "Custom Hardware Finishes",
      ],
      leatherType: "Premium Full-Grain Cowhide Leather",
      collarWidth: "20 mm to 40 mm",
      collarLength: "25 cm to 70 cm",
      airtagCompatibility: "Compatible with Apple AirTag",
      closureType: "Adjustable Buckle Closure",
      hardwareMaterial: "Solid Brass Hardware",
      stitchingType: "Heavy-Duty Contrast Stitching",
      edgeFinish: "Hand-Burnished Edges",
      liningMaterial: "Soft Leather Backing",
      availableColors: [
        "Brown",
        "Black",
        "Tan",
        "Cognac",
        "Dark Brown",
        "Custom Colors Available",
      ],
      suitableFor: ["Small Dogs", "Medium Dogs", "Large Dogs", "Cats"],
      features: [
        "Integrated AirTag Holder",
        "Premium Full-Grain Leather",
        "Solid Brass Buckle and D-Ring",
        "Comfortable Everyday Wear",
        "Handcrafted Construction",
        "Water-Resistant Leather Finish",
      ],
      unitWeight: "0.15 kg to 0.35 kg",
    },
  },
];

export default PET_ACCESSORIES;
